import test from 'node:test';
import assert from 'node:assert/strict';
import {designerPlan,designInspection} from '../src/designer.js';
import {constrainSketch,snapSketchPoint} from '../src/sketch.js';
import {Site,coordKey} from '../src/site.js';
import {emptyProject} from '../src/codec.js';
import {Resources} from '../src/resources.js';
import {buildMesh} from '../src/mesh.js';
const state={Name:'minecraft:oak_planks'};
function fixture(){const s=new Site({...emptyProject(),size:[80,30,80]});for(const [id,min,width]of [['a',[2,3,2],2],['b',[8,6,2],3],['c',[20,9,2],2]]){const cells=Array.from({length:width},(_,i)=>[min[0]+i,min[1],min[2]]);s.operations(cells.map(pos=>({type:'set',pos,state})),{});s.design.objects.push({id,name:id,min,max:[min[0]+width-1,min[1],min[2]],cells:cells.map(p=>coordKey(...p))});}return s;}
function apply(s,p){const before=structuredClone(s.design);s.operations(p.operations,{allowTerrain:true,allowExisting:true});if(!p.operations.length)s.undo.push({overlay:s.overlay,size:s.size,design:before});s.design=p.design;}
test('align and distribute preserve individual objects, snap dimensions and prepare without mutation',()=>{const s=fixture(),before=s.pack(),plan=designerPlan(s,{operation:'align',objectIds:['a','b','c'],axis:'y'});assert.deepEqual(s.pack(),before);apply(s,plan);assert.ok(s.design.objects.every(o=>o.min[1]===3));assert.equal(s.design.objects.length,3);s.restore('undo');assert.deepEqual(s.design,before.design);const p=designerPlan(s,{operation:'distribute',objectIds:['a','b','c'],axis:'x',distribution:'gaps'});apply(s,p);const o=s.design.objects.sort((a,b)=>a.min[0]-b.min[0]);assert.equal(o[0].min[0],2);assert.equal(o[2].min[0],20);const gaps=o.slice(1).map((o,i)=>o.min[0]-s.design.objects[i].max[0]-1);assert.ok(Math.abs(gaps[0]-gaps[1])<=1);});
test('arrays, path arrays, circular arrays and mirror keep block states and membership',()=>{for(const operation of ['array','pathArray','radialArray','mirror']){const s=fixture(),config={operation,objectIds:['a'],count:3,step:[0,0,5],axis:'z',plane:6,path:[[30,3,10],[30,3,15],[30,3,20]],spacing:5,center:[40,3,40],radius:8};const p=designerPlan(s,config);apply(s,p);assert.equal(s.design.objects.length,operation==='array'||operation==='mirror'?operation==='array'?5:4:6);for(const o of s.design.objects)assert.ok(o.cells.every(k=>s.at([k%4096,Math.floor(k/16777216),Math.floor(k/4096)%4096])));}});
test('associated instances synchronize material edits and can detach',()=>{const s=fixture();apply(s,designerPlan(s,{operation:'instance',objectIds:['a'],count:3,step:[0,0,8]}));const original=s.design.objects.find(o=>o.id==='a'),clones=s.design.objects.filter(o=>o.instanceOf===original.instanceOf&&o.id!=='a');assert.equal(clones.length,2);s.operations([{type:'set',pos:[2,3,2],state:{Name:'minecraft:glass'}}],{});apply(s,designerPlan(s,{operation:'syncInstances',objectIds:['a']}));for(const o of clones)assert.equal(s.palette[s.at(o.min).state].Name,'minecraft:glass');apply(s,designerPlan(s,{operation:'detachInstance',objectIds:[clones[0].id]}));assert.equal(s.design.objects.find(o=>o.id===clones[0].id).instanceOf,undefined);});
test('boundary pushpull expands and contracts only selected cells',()=>{const s=fixture();apply(s,designerPlan(s,{operation:'pushpull',objectIds:['a'],axis:'x',distance:3}));assert.equal(s.design.objects.find(o=>o.id==='a').max[0],6);assert.ok(s.at([6,3,2]));s.restore('undo');apply(s,designerPlan(s,{operation:'pushpull',objectIds:['a'],axis:'x',distance:-1}));assert.equal(s.at([3,3,2]),null);assert.ok(s.at([8,6,2]));});
test('closed offset produces independent reusable guide; boolean works by exact voxel occupancy',()=>{const s=fixture();s.design.guides=[{id:'rect',name:'矩形',recipe:{kind:'rectangle',plane:'xz',state},points:[[30,3,30],[34,3,30],[34,3,34],[30,3,34],[30,3,30]]}];const p=designerPlan(s,{operation:'offset',guideId:'rect',distance:2,guidesOnly:true},new Set([state.Name]));assert.equal(p.operations.length,0);assert.equal(p.design.guides.length,2);assert.equal(Math.min(...p.guide.map(p=>p[0])),28);const a=s.design.objects[0],b={id:'tool',name:'tool',min:[3,3,2],max:[3,3,2],cells:[coordKey(3,3,2)]};s.design.objects.push(b);apply(s,designerPlan(s,{operation:'boolean',objectIds:['a','tool'],mode:'subtract',consumeTool:true}));assert.equal(s.at([3,3,2]),null);assert.ok(s.at([2,3,2]));});
test('inspection returns exact dimensions layers materials and viewport isolation leaves data untouched',()=>{const s=fixture(),p=designInspection(s,{objectIds:['a']});assert.equal(p.blockCount,2);assert.deepEqual(p.size,[2,1,1]);assert.equal(p.layers[3].materials[state.Name],2);const before=s.pack(),resources=new Resources(),all=buildMesh(s,resources),isolated=buildMesh(s,resources,{isolateKeys:new Set(s.design.objects[0].cells)});assert.ok(all.triangles>isolated.triangles);assert.deepEqual(s.pack(),before);});
test('sketch plane grid parallel perpendicular symmetry and guide snapping are deterministic',()=>{const base={kind:'line',plane:'xz',points:[[1.2,2,1.1],[5.1,4,4.2]],planeLock:true,snap:.5};const horizontal=constrainSketch({...base,constraint:'horizontal'});assert.equal(horizontal.points[1][1],2);assert.equal(horizontal.points[1][2],1);const p=constrainSketch({...base,constraint:'perpendicular',referencePoints:[[0,2,0],[4,2,0]]});assert.equal(p.points[1][0],p.points[0][0]);const b=constrainSketch({kind:'bezier',plane:'xz',points:[[0,1,0],[2,1,4],[8,1,0],[10,1,2]],constraint:'symmetric'});assert.deepEqual(b.points[2],[8,1,-2]);assert.deepEqual(snapSketchPoint([2.2,3,2.1],{guides:[{points:[[2,3,2],[10,3,2]]}]}),[2,3,2]);});

test('instance relationships and new guides survive portable save reopening; locked edits reject',()=>{const s=fixture();apply(s,designerPlan(s,{operation:'instance',objectIds:['a'],count:2,step:[0,0,8]}));const reopened=Site.unpack(JSON.parse(JSON.stringify(s.pack())));assert.deepEqual(reopened.design,s.design);const master=reopened.design.objects.find(o=>o.id==='a');master.locked=true;assert.throws(()=>designerPlan(reopened,{operation:'array',objectIds:['a'],count:2,step:[0,0,8]}),/锁定/);assert.equal(designInspection(reopened,{objectIds:['a']}).blockCount,2);});
