import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyProject} from '../src/codec.js';
import {Site} from '../src/site.js';
import {Resources} from '../src/resources.js';
import {buildMesh} from '../src/mesh.js';
import {ChunkMesher} from '../src/chunk-mesh.js';
import {lineCells,brushCells,constrainLine} from '../src/brush.js';
function sample(){const p=emptyProject('跨区测试');p.size=[33,3,3];p.palette=[{Name:'minecraft:stone'}];p.blocks=[{pos:[15,0,0],state:0},{pos:[16,0,0],state:0},{pos:[32,0,0],state:0}];return new Site(p);}
test('chunk geometry matches full mesh including cross-chunk neighbor faces',()=>{const s=sample(),r=new Resources(),m=new ChunkMesher(),opts={mode:'after',cut:4095};const full=m.render(s,r,opts);assert.equal(full.triangles,buildMesh(s,r,opts).triangles);s.operations([{type:'erase',min:[16,0,0],max:[16,0,0]}],{allowTerrain:true,allowExisting:true});m.changed(s);const patch=m.render(s,r,opts);assert.equal(patch.reset,false);assert.ok(patch.chunks.some(c=>c.key==='0,0,0'));assert.ok(patch.chunks.some(c=>c.key==='1,0,0'));assert.equal(patch.triangles,buildMesh(s,r,opts).triangles);assert.ok(!patch.chunks.some(c=>c.key==='2,0,0'));s.restore('undo');m.changed(s);assert.equal(m.render(s,r,opts).triangles,full.triangles);});
test('painting above scene height keeps full-view cache instead of rebuilding terrain',()=>{const s=sample(),r=new Resources(),m=new ChunkMesher();m.render(s,r,{mode:'after',cut:2});s.operations([{type:'set',pos:[12,4,1],state:{Name:'minecraft:glass'}}]);m.changed(s);const patch=m.render(s,r,{mode:'after',cut:4});assert.equal(patch.reset,false);assert.ok(patch.stats.candidates<10);});
test('view changes rebuild correctly and untouched renders return no geometry',()=>{const s=sample(),r=new Resources(),m=new ChunkMesher();m.render(s,r,{mode:'after',cut:4095});assert.equal(m.render(s,r,{mode:'after',cut:4095}).chunks.length,0);s.operations([{type:'set',pos:[1,1,0],state:{Name:'minecraft:glass'}}]);m.changed(s);for(const mode of ['before','diff','removed','after']){const result=m.render(s,r,{mode,cut:4095});assert.equal(result.triangles,buildMesh(s,r,{mode,cut:4095}).triangles);}});
test('a continuous brush stroke is a single undo and protected positions are skipped',()=>{const s=sample();s.beginStroke();s.operations([{type:'set',pos:[1,1,0],state:{Name:'minecraft:glass'}}]);s.operations([{type:'set',pos:[2,1,0],state:{Name:'minecraft:glass'}}]);s.operations([{type:'erase',min:[15,0,0],max:[15,0,0]}],{skipLocked:true});s.endStroke();assert.equal(s.undo.length,1);assert.equal(s.overlay.size,2);assert.equal(s.summary().skipped,1);s.restore('undo');assert.equal(s.overlay.size,0);s.restore('redo');assert.equal(s.overlay.size,2);});
test('brush interpolates gaps, respects fixed-plane size and supports straight lines',()=>{assert.deepEqual(lineCells([0,1,0],[4,1,0]),[[0,1,0],[1,1,0],[2,1,0],[3,1,0],[4,1,0]]);assert.equal(brushCells([5,8,5],1,3,'square').length,9);assert.equal(brushCells([5,8,5],1,3,'circle').length,5);assert.ok(brushCells([5,8,5],1,5).every(p=>p[1]===8));assert.deepEqual(constrainLine([1,2,3],[7,2,5],1),[7,2,3]);});
test('different transparent materials retain the separating interface',()=>{const p=emptyProject();p.size=[2,1,1];p.palette=[{Name:'minecraft:glass'},{Name:'minecraft:ice'}];p.blocks=[{pos:[0,0,0],state:0},{pos:[1,0,0],state:1}];assert.equal(buildMesh(new Site(p),new Resources()).triangles,24);});
