import test from 'node:test';import assert from 'node:assert/strict';import {Site} from '../src/site.js';import {emptyProject} from '../src/codec.js';import {designerPlan} from '../src/designer.js';
const slab={Name:'minecraft:oak_slab',Properties:{type:'top',waterlogged:'false'}},stair={Name:'minecraft:oak_stairs',Properties:{facing:'east',half:'top',shape:'outer_left',waterlogged:'false'}},target={Name:'minecraft:stone_bricks'},available=new Set(['minecraft:stone_bricks','minecraft:stone_brick_slab','minecraft:stone_brick_stairs']);
test('selection material preview retains geometry properties and ignores surrounding terrain',()=>{const site=new Site({...emptyProject(),size:[8,8,8],palette:[slab,stair,{Name:'minecraft:dirt'}],blocks:[{pos:[1,1,1],state:0},{pos:[2,1,1],state:1},{pos:[1,0,1],state:2}]});const before=site.pack(),plan=designerPlan(site,{operation:'paint',selection:{min:[1,0,1],max:[2,1,1],members:[[1,1,1],[2,1,1]]},state:target},available);assert.deepEqual(site.pack(),before);assert.equal(plan.operations.length,2);assert.equal(plan.operations[0].state.Name,'minecraft:stone_brick_slab');assert.equal(plan.operations[0].state.Properties.type,'top');assert.equal(plan.operations[1].state.Name,'minecraft:stone_brick_stairs');assert.deepEqual(plan.operations[1].state.Properties,stair.Properties);assert.ok(plan.operations.every(op=>op.pos[1]===1));});
test('missing target shapes and block entities stay unchanged with explicit counts',()=>{const site=new Site({...emptyProject(),size:[8,8,8],palette:[slab,{Name:'minecraft:chest'}],blocks:[{pos:[1,1,1],state:0},{pos:[2,1,1],state:1,nbt:{keep:true}}]});const plan=designerPlan(site,{operation:'paint',selection:{min:[1,1,1],max:[2,1,1]},state:{Name:'minecraft:glass'}},new Set(['minecraft:glass']));assert.equal(plan.operations.length,0);assert.equal(plan.materialChange.skipped,2);assert.ok(plan.warnings.length>0);});

import {EngineWorkspace} from '../../local-engine/workspace.mjs';
test('shared material replacement prepare is readonly and commit preserves NBT terrain and undo',async()=>{const engine=new EngineWorkspace();try{const fixture={...emptyProject(),size:[8,8,8],palette:[slab,stair,{Name:'minecraft:dirt'}],blocks:[{pos:[1,1,1],state:0},{pos:[2,1,1],state:1},{pos:[1,0,1],state:2}]};await engine.call('import',{name:'selected.json',bytes:new TextEncoder().encode(JSON.stringify(fixture)).buffer});const before=await engine.call('api',{method:'workspace.describe'}),prep=await engine.call('api',{method:'construction.prepare',params:{expectedRevision:before.revision,type:'designer',policy:{allowExisting:true,allowTerrain:false},config:{operation:'paint',selection:{min:[1,1,1],max:[2,1,1]},state:{Name:'minecraft:glass'},retainShape:false}}});assert.ok(prep.ok,prep.error?.message);assert.equal(prep.value.materialChange.changed,2);assert.equal((await engine.call('api',{method:'workspace.describe'})).revision,before.revision);const done=await engine.call('api',{method:'construction.commit',params:{expectedRevision:before.revision,id:prep.value.id,policy:{allowExisting:true,allowTerrain:false}}});assert.ok(done.ok,done.error?.message);assert.equal((await engine.call('api',{method:'scene.getBlocks',params:{positions:[[1,0,1]]}})).value[0].state.Name,'minecraft:dirt');await engine.call('api',{method:'history.undo',params:{expectedRevision:done.revision}});assert.deepEqual((await engine.call('api',{method:'scene.getBlocks',params:{positions:[[1,1,1]]}})).value[0].state,slab);}finally{await engine.close();}});

test('specific source selection leaves mixed materials and terrain outside the match unchanged',()=>{const site=new Site({...emptyProject(),size:[8,8,8],palette:[slab,stair,{Name:'minecraft:glass'}],blocks:[{pos:[1,1,1],state:0},{pos:[2,1,1],state:1},{pos:[3,1,1],state:2}]});const before=site.pack(),plan=designerPlan(site,{operation:'paint',selection:{min:[1,1,1],max:[3,1,1]},state:target,sourceName:slab.Name},available);assert.deepEqual(site.pack(),before);assert.equal(plan.operations.length,1);assert.equal(plan.operations[0].state.Name,'minecraft:stone_brick_slab');assert.equal(plan.materialChange.matched,1);assert.equal(plan.materialChange.excluded,2);assert.equal(plan.materialChange.sources.length,3);const missing=designerPlan(site,{operation:'paint',selection:{min:[1,1,1],max:[3,1,1]},state:target,sourceName:'minecraft:missing'},available);assert.equal(missing.operations.length,0);assert.equal(missing.materialChange.excluded,3);});
