import {DesignAPI} from '../src/foundation.js';
import {Resources} from '../src/resources.js';
import test from 'node:test';import assert from 'node:assert/strict';import {brushPlan,toolMask} from '../src/tool-mask.js';import {Site,coordKey} from '../src/site.js';import {emptyProject} from '../src/codec.js';
const descriptors=new Map([['minecraft:stone_bricks',{choices:{}}],['minecraft:stone_brick_stairs',{choices:{facing:['north','east','south','west'],half:['top','bottom'],shape:['straight','inner_left'],waterlogged:['true','false']}}],['minecraft:stone_brick_slab',{choices:{type:['top','bottom','double'],waterlogged:['true','false']}}]]),mat={Name:'minecraft:stone_bricks'};
function scene(){const p=emptyProject();p.size=[8,5,8];p.palette=[{Name:'minecraft:oak_stairs',Properties:{facing:'west',half:'top',shape:'inner_left',waterlogged:'false'}},{Name:'minecraft:oak_slab',Properties:{type:'top',waterlogged:'false'}},{Name:'minecraft:chest',Properties:{facing:'north',type:'single',waterlogged:'false'}},{Name:'minecraft:water'}];p.blocks=[{pos:[1,1,1],state:0},{pos:[2,1,1],state:1},{pos:[3,1,1],state:2,nbt:{t:10,v:{id:{t:8,v:'minecraft:chest'},Value:{t:4,v:'9223372036854775807'}}}},{pos:[4,1,1],state:3}];return new Site(p);}
test('painting retains stairs/slab geometry, does not fill air/water, skips block-entity material loss, and undoes',()=>{const s=scene(),snapshot=s.pack(),plan=brushPlan(s,{points:[[1,1,1],[2,1,1],[3,1,1],[4,1,1],[5,1,1]],mode:'paint',state:mat},descriptors);assert.equal(plan.operations.length,2);assert.equal(plan.filtered,3);assert.deepEqual(plan.operations[0].state.Properties,s.palette[0].Properties);assert.equal(plan.operations[0].state.Name,'minecraft:stone_brick_stairs');assert.equal(plan.operations[1].state.Properties.type,'top');s.operations(plan.operations,{allowExisting:true});s.restore('undo');assert.deepEqual(s.pack().overlay,snapshot.overlay);assert.deepEqual(s.at([3,1,1]).nbt,snapshot.base.blocks[2].nbt);});
test('matching material, exact-member selection, height and surface conditions combine',()=>{const s=scene(),mask={selection:{members:[coordKey(1,1,1),coordKey(2,1,1)]},matchName:'minecraft:oak_stairs',minY:1,maxY:1,surface:true},plan=brushPlan(s,{points:[[1,1,1],[2,1,1],[3,1,1]],mode:'paint',state:mat,mask},descriptors);assert.equal(plan.operations.length,1);assert.deepEqual(plan.operations[0].pos,[1,1,1]);const filled=new Site(emptyProject());filled.operations([{type:'fill',min:[1,1,1],max:[3,3,3],state:mat}],{});assert.equal(toolMask(filled,{surface:true})([2,2,2]),false);assert.equal(toolMask(filled,{surface:true})([1,2,2]),true);assert.throws(()=>toolMask(s,{minY:4096}),/范围/);});
test('new drawing only fills empty cells and missing variants do not invent shape IDs',()=>{const s=scene();assert.equal(brushPlan(s,{points:[[1,1,1],[5,1,1]],state:mat,mask:{emptyOnly:true}}).operations.length,1);assert.equal(brushPlan(s,{points:[[1,1,1]],mode:'paint',state:{Name:'minecraft:glass'}},descriptors).operations.length,0);assert.throws(()=>brushPlan(s,{points:[[1,1,1]],mode:'draw'}),/材质/);});
test('same block-entity type changes preserve typed NBT when state copying is disabled',()=>{const s=scene(),plan=brushPlan(s,{points:[[3,1,1]],mode:'paint',state:{Name:'minecraft:chest',Properties:{facing:'east'}},preserveProperties:false},descriptors);assert.equal(plan.operations.length,1);s.operations(plan.operations,{allowExisting:true});assert.equal(s.palette[s.at([3,1,1]).state].Properties.facing,'east');assert.equal(s.at([3,1,1]).nbt.v.Value.v,'9223372036854775807');});

test('public brush API shares masks, validates revisions, replays requests, and stages world-coordinate edits',()=>{const site=scene();site.origin=[-20,64,30];site.originConfirmed=true;const api=new DesignAPI({getSite:()=>site,resources:()=>new Resources()});assert.ok(api.execute({method:'workspace.describe'}).value.methods.includes('edit.brush'));const params={expectedRevision:0,mode:'paint',points:[[-19,65,31]],state:mat,space:'world',mask:{selection:{members:[[-19,65,31]]},minY:65,maxY:65,surface:true},policy:{allowExisting:true}},request={id:'paint-once',method:'edit.brush',params};const r=api.execute(request);assert.ok(r.ok,r.error?.message);assert.equal(site.palette[site.at([1,1,1]).state].Name,'minecraft:stone_brick_stairs');assert.equal(api.execute(request).revision,r.revision);assert.equal(api.execute({method:'edit.brush',params}).ok,false);const started=api.execute({method:'transaction.begin',params:{expectedRevision:api.revision,policy:{allowExisting:true}}});const tx=started.value.transactionId;const staged=api.execute({method:'edit.brush',params:{transactionId:tx,mode:'paint',points:[[2,1,1]],state:mat}});assert.ok(staged.ok,staged.error?.message);assert.equal(site.palette[site.at([2,1,1]).state].Name,'minecraft:oak_slab');assert.ok(api.execute({method:'transaction.commit',params:{transactionId:tx}}).ok);assert.equal(site.palette[site.at([2,1,1]).state].Name,'minecraft:stone_brick_slab');});

test('shape retention does not replace an unsupported door/pane with a full cube',()=>{const s=new Site(emptyProject());s.operations([{type:'set',pos:[1,1,1],state:{Name:'minecraft:oak_door',Properties:{half:'lower',facing:'north',hinge:'left',open:'false',powered:'false'}}},{type:'set',pos:[2,1,1],state:{Name:'minecraft:glass_pane',Properties:{north:'true',east:'false',south:'false',west:'false',waterlogged:'false'}}}],{});const plan=brushPlan(s,{points:[[1,1,1],[2,1,1]],mode:'paint',state:mat},descriptors);assert.equal(plan.operations.length,0);assert.equal(plan.filtered,2);});
