const terms={cut:'切制',polished:'磨制',limestone:'石灰岩',andesite:'安山岩',diorite:'闪长岩',granite:'花岗岩',deepslate:'深板岩',stone:'石',bricks:'砖',brick:'砖',slab:'台阶',stairs:'楼梯',wall:'墙',pillar:'柱',layered:'层纹',oak:'橡木',spruce:'云杉',cherry:'樱花木',dark:'深色',planks:'木板',log:'原木',stripped:'去皮',glass:'玻璃',pane:'片',white:'白色',black:'黑色',red:'红色',blue:'蓝色',green:'绿色',concrete:'混凝土',terracotta:'陶瓦',water:'水',grass:'草',block:'方块',dirt:'泥土',leaves:'树叶',gold:'金',iron:'铁',copper:'铜',sail:'风帆',shaft:'传动轴',cogwheel:'齿轮',large:'大型',bearing:'轴承',windmill:'风车',lantern:'灯笼',fence:'围栏',door:'门',sand:'沙',sandstone:'砂岩',tuff:'凝灰岩',calcite:'方解石',moss:'苔藓',veridium:'辉绿岩',asurine:'皓蓝岩',small:'小型',cutout:'镂空',smooth:'平滑',casing:'机壳',barrel:'木桶',crafting:'工作',table:'台',light:'浅色',gray:'灰色',yellow:'黄色',pink:'粉色',purple:'紫色'};
export function humanName(id,label){if(label&&/[\u3400-\u9fff]/.test(label))return label;const words=id.split(':').at(-1).split('/').at(-1).split('_').map(w=>terms[w]||w);return words.join(words.every(w=>/[\u3400-\u9fff]/.test(w))?'':' ').replaceAll('砖砖','砖').trim();}
export const builtInCategories=[['all','全部方块'],['used','场景使用'],['favorites','收藏'],['stone','石材与砖'],['wood','木材'],['metal','金属'],['glass','玻璃与采光'],['stairs','楼梯'],['slab','台阶'],['pillar','柱与墙'],['decoration','装饰'],['plants','植物'],['mechanical','机械外观'],['fluid','流体']];
export function features(id){const n=id.split(':').at(-1),tags=[];for(const[k,re]of [['stone',/stone|brick|andesite|diorite|granite|tuff|calcite|terracotta|asurine|veridium/],['wood',/oak|spruce|birch|cherry|mangrove|jungle|acacia|bamboo|plank|log|wood/],['metal',/iron|gold|copper|metal|steel/],['glass',/glass|pane/],['stairs',/stairs$/],['slab',/slab$/],['pillar',/pillar|wall$|fence$/],['decoration',/lantern|lamp|door|trapdoor|carpet|pot|banner|chain|torch/],['plants',/leaves|flower|grass(?!_block)|sapling|petal|fern|vine|moss/],['mechanical',/shaft|cogwheel|bearing|sail|wheel|belt|piston|gantry|mechanical|casing/],['fluid',/water|lava/]])if(re.test(n))tags.push(k);return tags;}
export function assetPreferences(){return{schema:'craftstudio-assets/1',categories:[],assignments:{},aliases:{},favorites:[],recent:[]};}
export function assetMatches(item,{category='all',query='',source='all',color='all'},prefs){if(source!=='all'&&item.source!==source)return false;if(color!=='all'&&item.color!==color)return false;if(query&&!(item.name+' '+item.id+' '+(prefs.aliases[item.id]||'')).toLowerCase().includes(query.toLowerCase()))return false;if(category==='favorites')return prefs.favorites.includes(item.id);if(category==='used')return item.used;if(category.startsWith('custom:')){const children=new Set([category]);let changed=true;while(changed){changed=false;for(const c of prefs.categories)if(children.has(c.parent)&&!children.has(c.id)){children.add(c.id);changed=true;}}return(prefs.assignments[item.id]||[]).some(id=>children.has(id));}return category==='all'||item.tags.includes(category);}
export function catalogue(site,resources){const map=new Map(),labels=new Map(resources.catalogue('').map(i=>[i.id,i.label]));const add=(state,used=false)=>{if(['minecraft:air','minecraft:cave_air','minecraft:void_air','minecraft:structure_void'].includes(state.Name)||state.Name.startsWith('craftstudio:'))return;let item=map.get(state.Name);if(!item){const id=state.Name,n=id.split(':').at(-1);item={id,name:humanName(id,labels.get(id)),source:id.split(':')[0],tags:features(id),used,states:[],choices:{},color:/white|limestone|calcite|quartz/.test(n)?'light':/dark|black|deepslate/.test(n)?'dark':/red|^bricks$|copper|oak|spruce|birch|wood|plank/.test(n)?'warm':/blue|asurine|water/.test(n)?'blue':/green|veridium|leaves|grass|moss/.test(n)?'green':'neutral'};map.set(id,item);}item.used||=used;if(!item.states.some(s=>JSON.stringify(s.Properties||{})===JSON.stringify(state.Properties||{})))item.states.push(state);for(const[k,v]of Object.entries(state.Properties||{})){item.choices[k]||=[];if(!item.choices[k].includes(String(v)))item.choices[k].push(String(v));}};
 for(const s of site.palette)add(s,true);for(const i of resources.catalogue(''))add({Name:i.id});
 for(const Name of ['minecraft:stone_bricks','minecraft:oak_planks','minecraft:glass','minecraft:stone_brick_stairs','minecraft:stone_brick_slab','minecraft:oak_log','minecraft:lantern','minecraft:water'])add({Name});
 for(const item of map.values()){const n=item.id.split(':')[1],defaults=/stairs$/.test(n)?{facing:['north','east','south','west'],half:['bottom','top'],shape:['straight','inner_left','inner_right','outer_left','outer_right'],waterlogged:['false','true']}:/slab$/.test(n)?{type:['bottom','top','double'],waterlogged:['false','true']}:/log$|pillar$|shaft$/.test(n)?{axis:['y','x','z']}:{};for(const[k,v]of Object.entries(defaults))item.choices[k]=[...new Set([...(item.choices[k]||[]),...v])];const raw=resources.json('assets/'+item.source+'/blockstates/'+item.id.split(':')[1]+'.json');for(const key of Object.keys(raw.variants||{}))for(const pair of key.split(',')){const[k,v]=pair.split('=');if(v){item.choices[k]||=[];for(const value of v.split('|'))if(!item.choices[k].includes(value))item.choices[k].push(value);}}if(!Object.keys(item.states[0]?.Properties||{}).length&&Object.keys(item.choices).length)item.states[0]={Name:item.id,Properties:Object.fromEntries(Object.entries(item.choices).map(([k,v])=>[k,v[0]]))};}
 return[...map.values()].sort((a,b)=>Number(b.used)-Number(a.used)||a.name.localeCompare(b.name,'zh-CN'));
}
