export function brushUI({$,library,notice}){
 const host=$('cad-brush-settings'),controls=document.createElement('section');controls.innerHTML='<label>画笔用途<select id="brush-mode"><option value="draw">绘制新方块</option><option value="paint">涂改已有方块</option></select></label><div id="brush-paint-options" hidden><label class="check"><input id="brush-retain-shape" type="checkbox" checked>保留楼梯、半砖等形态</label><label class="check"><input id="brush-preserve-props" type="checkbox" checked>保留朝向与连接状态</label></div><details><summary>作用范围条件</summary><label class="check"><input id="brush-in-selection" type="checkbox">仅当前选择</label><label class="check"><input id="brush-surface" type="checkbox">仅外露表面</label><label class="check"><input id="brush-match-picked" type="checkbox">仅起笔时取样的材料</label><label class="check"><input id="brush-empty" type="checkbox" checked>仅空位（绘制）</label><div class="row"><label>局部 Y 下限<input id="brush-min-y" type="number" min="0" max="4095" placeholder="不限"></label><label>局部 Y 上限<input id="brush-max-y" type="number" min="0" max="4095" placeholder="不限"></label></div></details><p id="brush-conditions" class="small"></p><details><summary>画笔预设</summary><select id="brush-preset"><option value="">选择预设</option></select><input id="brush-preset-name" placeholder="例如：屋顶表面涂改"><div class="row"><button id="brush-save-preset">保存预设</button><button id="brush-load-preset">载入预设</button></div></details><p class="small">涂改不填空气或流体，缺少形态变体会保留原方块。操作仍尊重场地与对象保护。</p>';host.append(controls);let presets=[],tool='paint';
 const fields=['brush-mode','brush-size','brush-shape','brush-retain-shape','brush-preserve-props','brush-in-selection','brush-surface','brush-match-picked','brush-empty','brush-min-y','brush-max-y'];
 function config(){const mask={surface:$('brush-surface').checked,matchPicked:$('brush-match-picked').checked,inSelection:$('brush-in-selection').checked,emptyOnly:tool!=='erase'&&$('brush-mode').value==='draw'&&$('brush-empty').checked};for(const[a,id]of [['minY','brush-min-y'],['maxY','brush-max-y']])if($(id).value!=='')mask[a]=Number($(id).value);return{mode:$('brush-mode').value,mask,retainShape:$('brush-retain-shape').checked,preserveProperties:$('brush-preserve-props').checked};}
 function update(){const c=config();$('brush-mode').closest('label').hidden=tool==='erase';$('brush-paint-options').hidden=c.mode!=='paint'||tool==='erase';$('brush-empty').closest('label').hidden=c.mode!=='draw'||tool==='erase';$('brush-conditions').textContent=(tool==='erase'?'连续擦除':c.mode==='paint'?'涂改已有':'连续新增')+' · '+[c.mask.inSelection?'当前选择':'',c.mask.surface?'表面':'',c.mask.matchPicked?'取样材料':'',c.mask.emptyOnly?'空位':'',c.mask.minY!==undefined||c.mask.maxY!==undefined?'Y '+(c.mask.minY??0)+'–'+(c.mask.maxY??4095):''].filter(Boolean).join(' / ');window.dispatchEvent(new Event('craftstudio-brush-settings'));}
 $('brush-mode').onchange=()=>{$('brush-surface').checked=$('brush-mode').value==='paint';update();};for(const id of fields)if(id!=='brush-mode')$(id).addEventListener('input',update);
 function options(){$('brush-preset').replaceChildren(...[{name:'选择预设',id:''},...presets.map((p,i)=>({name:p.name,id:String(i)}))].map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;return o;}));}
 $('brush-save-preset').onclick=async()=>{try{const name=$('brush-preset-name').value.trim();if(!name)throw Error('请给预设起一个名称');const values=Object.fromEntries(fields.map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value])),i=presets.findIndex(p=>p.name===name),next=[...presets];if(i<0)next.push({name,values});else next[i]={name,values};await library.preference('brush-presets',{schema:1,presets:next});presets=next;options();notice('画笔预设已保存');}catch(e){notice(e.message,true);}};
 $('brush-load-preset').onclick=()=>{const p=presets[Number($('brush-preset').value)];if(!p||$('brush-preset').value==='')return;for(const[id,value]of Object.entries(p.values))if(fields.includes(id)){if($(id).type==='checkbox')$(id).checked=value;else $(id).value=value;}update();notice('已载入画笔预设；当前选择在起笔时读取');};
 library.preference('brush-presets').then(p=>{presets=p?.schema===1?p.presets||[]:[];options();}).catch(()=>{});update();return{config,toolChanged:value=>{tool=value;update();}};
}
