import { gunzipSync, gzipSync, unzlibSync } from 'fflate';

export const tag=(t,v)=>({t,v});
export const stateKey=s=>s.Name+'['+Object.entries(s.Properties||{}).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join(',')+']';
export function plain(t){if(t.t===10)return Object.fromEntries(Object.entries(t.v).map(([k,v])=>[k,plain(v)]));if(t.t===9)return t.v[1].map(v=>plain(tag(t.v[0],v)));return t.v;}
function mutfEncode(s){const out=[];for(let i=0;i<s.length;i++){const n=s.charCodeAt(i);if(n&&n<128)out.push(n);else if(n<2048)out.push(192|(n>>6),128|(n&63));else out.push(224|(n>>12),128|((n>>6)&63),128|(n&63));}return Uint8Array.from(out);}
function mutfDecode(bytes){let s='';for(let i=0;i<bytes.length;){const c=bytes[i++];if(c<128)s+=String.fromCharCode(c);else if((c&224)===192)s+=String.fromCharCode(((c&31)<<6)|(bytes[i++]&63));else if((c&240)===224)s+=String.fromCharCode(((c&15)<<12)|((bytes[i++]&63)<<6)|(bytes[i++]&63));else if((c&248)===240){const n=((c&7)<<18)|((bytes[i++]&63)<<12)|((bytes[i++]&63)<<6)|(bytes[i++]&63);s+=String.fromCodePoint(n);}else throw Error('无效 NBT 字符编码');}return s;}
export function readNBT(input){
 let bytes=input instanceof Uint8Array?input:new Uint8Array(input);if(bytes[0]===31&&bytes[1]===139)bytes=gunzipSync(bytes);
 const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let at=0;
 function read(n){if(at+n>bytes.length)throw Error('NBT 文件截断');const b=bytes.subarray(at,at+n);at+=n;return b;}
 function num(type){const map={1:['getInt8',1],2:['getInt16',2],3:['getInt32',4],4:['getBigInt64',8],5:['getFloat32',4],6:['getFloat64',8]};const [fn,n]=map[type];if(at+n>bytes.length)throw Error('NBT 文件截断');const value=view[fn](at,false);at+=n;return type===4?value.toString():value;}
 function str(){if(at+2>bytes.length)throw Error('NBT 字符串截断');const length=view.getUint16(at,false);at+=2;return mutfDecode(read(length));}
 function payload(type,depth=0){if(depth>512)throw Error('NBT 嵌套过深');if(type>=1&&type<=6)return num(type);if(type===8)return str();if(type===10){const out={};while(true){const sub=read(1)[0];if(sub===0)return out;const name=str();Object.defineProperty(out,name,{value:tag(sub,payload(sub,depth+1)),enumerable:true,configurable:true,writable:true});}}
  if(type===9){const sub=read(1)[0],count=num(3);if(count<0||count>bytes.length||(sub===0&&count))throw Error('无效 NBT 列表');const items=[];for(let i=0;i<count;i++)items.push(payload(sub,depth+1));return[sub,items];}
  if([7,11,12].includes(type)){const count=num(3);if(count<0||count>bytes.length)throw Error('无效 NBT 数组');if(type===7)return Array.from(read(count));return Array.from({length:count},()=>num(type===11?3:4));}
  throw Error('不支持的 NBT 类型 '+type);
 }
 const type=read(1)[0];str();if(type!==10)throw Error('NBT 根节点必须为 Compound');return tag(type,payload(type));
}
export function writeNBT(root,compressed=true){
 let buffer=new Uint8Array(65536),at=0,view=new DataView(buffer.buffer);const strings=new Map();function ensure(n){if(at+n>buffer.length){const next=new Uint8Array(Math.max(buffer.length*2,at+n));next.set(buffer);buffer=next;view=new DataView(buffer.buffer);}}function bytes(b){ensure(b.length);buffer.set(b,at);at+=b.length;}function num(type,v){const map={1:['setInt8',1],2:['setInt16',2],3:['setInt32',4],4:['setBigInt64',8],5:['setFloat32',4],6:['setFloat64',8]};const[fn,n]=map[type];ensure(n);view[fn](at,type===4?BigInt(v):v,false);at+=n;}
 function str(s){let b=strings.get(s);if(!b){b=mutfEncode(s);if(b.length>65535)throw Error('NBT 字符串过长');if(strings.size<10000)strings.set(s,b);}ensure(2);view.setUint16(at,b.length,false);at+=2;bytes(b);}
 function payload(t){const v=t.v;if(t.t>=1&&t.t<=6){num(t.t,v);return;}if(t.t===8){str(v);return;}if(t.t===10){for(const[k,x]of Object.entries(v)){bytes(Uint8Array.of(x.t));str(k);payload(x);}bytes(Uint8Array.of(0));return;}if(t.t===9){bytes(Uint8Array.of(v[0]));num(3,v[1].length);for(const item of v[1])payload(tag(v[0],item));return;}if([7,11,12].includes(t.t)){num(3,v.length);if(t.t===7)bytes(Uint8Array.from(v));else for(const x of v)num(t.t===11?3:4,x);return;}throw Error('无效 NBT 类型');}
 bytes(Uint8Array.of(root.t));str('');payload(root);const result=buffer.slice(0,at);return compressed?gzipSync(result,{mtime:0}):result;
}
const AIR=new Set(['minecraft:air','minecraft:cave_air','minecraft:void_air']);
export function maskRuns(values){values.sort((a,b)=>a-b);const runs=[];for(const n of values){const last=runs.at(-1);if(last&&last[0]+last[1]===n)last[1]++;else runs.push([n,1]);}return runs;}
export function maskBlocks(mask,kind='eraseRuns'){const[w,,l]=mask.size;return(mask[kind]||[]).flatMap(([start,count])=>Array.from({length:count},(_,d)=>{const i=start+d;return[i%w,Math.floor(i/(w*l)),Math.floor(i/w)%l];}));}
export function emptyProject(name='新场地'){return{schema:1,name,size:[1,1,1],origin:[0,0,0],dataVersion:3955,palette:[],blocks:[],entities:[],metadata:{},warnings:[]};}
function paletteState(t){return plain(tag(10,t));}
function packed(data,bits,count,padded=false){const words=data.map(v=>BigInt.asUintN(64,BigInt(v))),mask=(1n<<BigInt(bits))-1n,per=Math.floor(64/bits);if(!words.length)return new Uint32Array(count);const out=new Uint32Array(count);for(let i=0;i<count;i++){const bit=i*bits,word=padded?Math.floor(i/per):Math.floor(bit/64),shift=padded?(i%per)*bits:bit%64;if(word>=words.length)throw Error('方块位数组截断');let value=words[word]>>BigInt(shift);if(!padded&&shift+bits>64)value|=words[word+1]<<BigInt(64-shift);out[i]=Number(value&mask);}return out;}
export function importNBT(bytes,name){let root=readNBT(bytes),r=root.v;const p=emptyProject(name);
 if(r.blocks&&(r.palette||r.palettes)){
  p.size=plain(r.size);p.dataVersion=r.DataVersion?.v||0;
  const pal=r.palette||tag(9,r.palettes.v[1][0]);p.palette=pal.v[1].map(paletteState);
  const skips=[],erasures=[],[w,,l]=p.size;for(const b of r.blocks.v[1]){const state=b.state.v;if(!p.palette[state])throw Error('方块调色板索引越界');const pos=plain(b.pos),linear=pos[0]+w*(pos[2]+l*pos[1]);if(p.palette[state].Name==='minecraft:structure_void'){skips.push(linear);continue;}if(AIR.has(p.palette[state].Name)){erasures.push(linear);continue;}const item={pos:plain(b.pos),state};if(b.nbt)item.nbt=b.nbt;p.blocks.push(item);}
  p.entities=(r.entities?.v[1]||[]).map(v=>tag(10,v));p.metadata.nativeExtra=Object.fromEntries(Object.entries(r).filter(([k])=>!['blocks','palette','size','entities','DataVersion'].includes(k)));p.metadata.sourceFormat='structure';if(skips.length||erasures.length)p.metadata.placementMask={schema:'craftstudio-placement-mask/1',size:[...p.size],skipCount:skips.length,eraseCount:erasures.length,skipRuns:maskRuns(skips),eraseRuns:maskRuns(erasures)};if(r.palettes)p.warnings.push('多调色板结构使用第一组；导出会采用这一组。');return p;
 }
 if(r.Regions){const lookup=new Map();p.dataVersion=r.MinecraftDataVersion?.v||0;
  for(const regionTag of Object.values(r.Regions.v)){const region=regionTag.v,pal=region.BlockStatePalette.v[1].map(paletteState),size=plain(region.Size),position=plain(region.Position),sizes=['x','y','z'].map(a=>size[a]),dims=sizes.map(Math.abs),offset=['x','y','z'].map((a,i)=>position[a]+Math.min(0,sizes[i]+1));const values=packed(region.BlockStates.v,Math.max(2,Math.ceil(Math.log2(pal.length))),dims[0]*dims[1]*dims[2]);const tiles=new Map((region.TileEntities?.v[1]||[]).map(v=>{const x=plain(tag(10,v));return[[x.x,x.y,x.z].join(','),tag(10,v)];}));for(let i=0;i<values.length;i++){const s=pal[values[i]];if(!s)throw Error('Litematica 调色板索引越界');if(AIR.has(s.Name))continue;const key=stateKey(s);if(!lookup.has(key)){lookup.set(key,p.palette.length);p.palette.push(s);}const local=[i%dims[0],Math.floor(i/(dims[0]*dims[2])),Math.floor(i/dims[0])%dims[2]],b={pos:local.map((v,a)=>v+offset[a]),state:lookup.get(key)};if(tiles.has(local.join(',')))b.nbt=tiles.get(local.join(','));p.blocks.push(b);}}
  normalize(p);p.metadata.sourceFormat='litematic';p.warnings.push('Litematica：保留方块及方块实体；实体、计划刻和多区域信息没有转换成原版 NBT。');return p;
 }
 if(r.Schematic){root=r.Schematic;r=root.v;}
 const section=r.Blocks?.v||r;if(section.Palette&&(section.Data||section.BlockData)){
  const mapping=plain(section.Palette);p.size=[r.Width.v,r.Height.v,r.Length.v];p.dataVersion=r.DataVersion?.v||0;p.palette=Array.from({length:Math.max(...Object.values(mapping))+1},()=>({Name:'minecraft:air'}));for(const[text,id]of Object.entries(mapping)){const m=text.match(/^([^[]+)(?:\[(.*)\])?$/);p.palette[id]={Name:m[1]};if(m[2])p.palette[id].Properties=Object.fromEntries(m[2].split(',').map(a=>a.split('=')));}const vals=[];let value=0,shift=0;for(let byte of (section.Data||section.BlockData).v){byte&=255;value|=(byte&127)<<shift;if(byte&128){shift+=7;if(shift>28)throw Error('无效 Sponge VarInt');}else{vals.push(value>>>0);value=shift=0;}}const[w,h,l]=p.size;if(vals.length!==w*h*l)throw Error('Sponge 方块数量与尺寸不符');const tiles=new Map();for(const be of section.BlockEntities?.v[1]||[]){const pos=plain(be.Pos);const data=be.Data||tag(10,Object.fromEntries(Object.entries(be).filter(([k])=>!['Pos','Id'].includes(k))));data.v.id=tag(8,be.Id?.v||'');tiles.set(pos.join(','),data);}for(let i=0;i<vals.length;i++){const s=vals[i];if(!p.palette[s])throw Error('Sponge 调色板索引越界');if(AIR.has(p.palette[s].Name))continue;const pos=[i%w,Math.floor(i/(w*l)),Math.floor(i/w)%l],b={pos,state:s};if(tiles.has(pos.join(',')))b.nbt=tiles.get(pos.join(','));p.blocks.push(b);}p.metadata.sourceFormat='schem';p.warnings.push('Sponge：保留方块及方块实体；实体和生物群系未转换。');return p;
 }
 throw Error('没有识别到结构；支持 Create/原版 NBT、Sponge schem 和 Litematica。');
}
function normalize(p){if(!p.blocks.length)return;const lo=[0,1,2].map(a=>Math.min(...p.blocks.slice(0,1).map(b=>b.pos[a]))),hi=[...lo];for(const b of p.blocks)for(let a=0;a<3;a++){lo[a]=Math.min(lo[a],b.pos[a]);hi[a]=Math.max(hi[a],b.pos[a]);}for(const b of p.blocks)b.pos=b.pos.map((v,a)=>v-lo[a]);p.size=hi.map((v,a)=>v-lo[a]+1);p.origin=lo;}
export function exportNBT(p,blocks=p.blocks,size=p.size){let states=[...p.palette];const mask=p.metadata?.placementMask;if(mask&&mask.size.every((n,a)=>n===size[a])&&blocks===p.blocks){const occupied=new Set(blocks.map(b=>b.pos.join(','))),extra=[];for(const[kind,Name]of [['skipRuns','minecraft:structure_void'],['eraseRuns','minecraft:air']]){let state=states.findIndex(s=>s.Name===Name);if(state<0){state=states.length;states.push({Name});}for(const pos of maskBlocks(mask,kind))if(!occupied.has(pos.join(',')))extra.push({pos,state});}blocks=[...blocks,...extra];}const palette=states.map(s=>{const v={Name:tag(8,s.Name)};if(s.Properties)v.Properties=tag(10,Object.fromEntries(Object.entries(s.Properties).map(([k,x])=>[k,tag(8,String(x))])));return v;});const list=blocks.map(b=>{const v={pos:tag(9,[3,b.pos]),state:tag(3,b.state)};if(b.nbt)v.nbt=b.nbt;return v;});const extra={...p.metadata?.nativeExtra};delete extra.palettes;return writeNBT(tag(10,{...extra,DataVersion:tag(3,p.dataVersion),size:tag(9,[3,size]),palette:tag(9,[10,palette]),blocks:tag(9,[10,list]),entities:tag(9,[10,(p.entities||[]).map(e=>e.v)])}));}
export function importMCA(bytes,name,lo,hi){const match=name.match(/r\.(-?\d+)\.(-?\d+)\.mca$/);if(!match)throw Error('MCA 文件名需要 r.X.Z.mca');const rx=+match[1],rz=+match[2],view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),p=emptyProject(name),lookup=new Map();if(lo.some((v,a)=>v>hi[a]))throw Error('区域起点不能大于终点');if(lo[0]<rx*512||hi[0]>=rx*512+512||lo[2]<rz*512||hi[2]>=rz*512+512)throw Error('选择的坐标超出这个 MCA 文件；一次只读取当前文件中的选区');p.size=hi.map((v,a)=>v-lo[a]+1);p.origin=lo;p.metadata.originConfirmed=true;
 for(let cz=Math.floor(lo[2]/16);cz<=Math.floor(hi[2]/16);cz++)for(let cx=Math.floor(lo[0]/16);cx<=Math.floor(hi[0]/16);cx++){const loc=view.getUint32(((cx&31)+(cz&31)*32)*4,false),offset=(loc>>>8)*4096;if(!offset)continue;if(offset+5>bytes.length)throw Error('MCA 区块记录截断');const n=view.getUint32(offset,false),kind=bytes[offset+4];if(kind&128)throw Error('该区块使用外置 MCC，请改用含地形的区域 NBT');let data=bytes.subarray(offset+5,offset+4+n);if(kind===2)data=unzlibSync(data);else if(kind!==1&&kind!==3)throw Error('尚未支持该区块压缩格式');const root=readNBT(data).v,r=root.Level?.v||root;p.dataVersion=root.DataVersion?.v||0;const tiles=new Map((r.block_entities||r.TileEntities)?.v[1]?.map(v=>{const d=plain(tag(10,v));return[[d.x,d.y,d.z].join(','),tag(10,v)];})||[]);for(const section of (r.sections||r.Sections)?.v[1]||[]){const sy=section.Y.v*16;if(sy>hi[1]||sy+15<lo[1])continue;const states=section.block_states?.v,palTag=states?.palette||section.Palette;if(!palTag){if(section.Blocks)throw Error('该区域使用 1.12 或更早的数值方块 ID，请先在 Minecraft 中升级副本再导入');continue;}const pal=palTag.v[1].map(paletteState),packedData=states?.data||section.BlockStates,values=packed(packedData?.v||[],Math.max(4,Math.ceil(Math.log2(pal.length))),4096,p.dataVersion>=2529);for(let i=0;i<4096;i++){const pos=[cx*16+i%16,sy+Math.floor(i/256),cz*16+Math.floor(i/16)%16];if(pos.some((v,a)=>v<lo[a]||v>hi[a]))continue;const state=pal[values[i]];if(!state||AIR.has(state.Name))continue;const key=stateKey(state);if(!lookup.has(key)){lookup.set(key,p.palette.length);p.palette.push(state);}const b={pos:pos.map((v,a)=>v-lo[a]),state:lookup.get(key)};if(tiles.has(pos.join(',')))b.nbt=tiles.get(pos.join(','));p.blocks.push(b);}}}
 p.metadata.sourceFormat='mca';p.warnings.push('MCA：只读当前文件的所选区域；保留方块及方块实体，不转换实体、光照和计划刻。');return p;
}
