import {constrainSketch} from './sketch.js';
import {coordKey,terrainType} from './site.js';
const axes={xz:[0,2],xy:[0,1],yz:[2,1]};
const distance=(a,b)=>Math.hypot(...a.map((n,i)=>n-b[i]));
export function bezier(points,t){let work=points.map(p=>[...p]);while(work.length>1)work=work.slice(0,-1).map((p,i)=>p.map((n,a)=>n*(1-t)+work[i+1][a]*t));return work[0];}
export function sampleFigure(config){const{kind='bezier',points,plane='xz'}=config;if(!Array.isArray(points)||points.length<2||points.some(p=>p.length!==3||p.some(n=>!Number.isFinite(n))))throw Error('请设置有效的控制点');const density=Math.max(1,Math.min(8,config.sampleDensity??8)),[a,b]=axes[plane]||axes.xz,out=[],add=p=>out.push(p);
 const segment=(p,q)=>{const n=Math.max(1,Math.ceil(distance(p,q)*density));if(n>16384)throw Error('单段过长，请拆分绘制');for(let i=0;i<=n;i++)add(p.map((v,k)=>v+(q[k]-v)*i/n));};
 if(kind==='line')segment(points[0],points.at(-1));
 else if(kind==='bezier'){if(points.length<3||points.length>8)throw Error('贝塞尔曲线需要 3–8 个控制点');const length=points.slice(1).reduce((n,p,i)=>n+distance(p,points[i]),0),n=Math.min(8192,Math.max(24,Math.ceil(length*density)));for(let i=0;i<=n;i++)add(bezier(points,i/n));}
 else if(kind==='rectangle'){const p=points[0],q=points[1],corners=[p,[...p],[...q],[...p]];corners[1][a]=q[a];corners[3][b]=q[b];for(let i=0;i<4;i++)segment(corners[i],corners[(i+1)%4]);}
 else if(kind==='polygon'){for(let i=0;i<points.length;i++)segment(points[i],points[(i+1)%points.length]);}
 else if(['circle','ellipse','arc'].includes(kind)){const c=points[0],radius=Math.hypot(points[1][a]-c[a],points[1][b]-c[b]),rx=kind==='ellipse'?Math.abs(points[1][a]-c[a]):radius,ry=kind==='ellipse'?Math.abs(points[1][b]-c[b]):radius;if(rx<.1||ry<.1)throw Error('半径过小，请拉开控制点');let start=0,end=2*Math.PI;if(kind==='arc'){if(points.length<3)throw Error('圆弧需要圆心、起点和终点');start=Math.atan2(points[1][b]-c[b],points[1][a]-c[a]);end=Math.atan2(points[2][b]-c[b],points[2][a]-c[a]);while(end<=start)end+=2*Math.PI;}const n=Math.max(24,Math.ceil((end-start)*Math.max(rx,ry)*density));if(n>16384)throw Error('图形范围过大，请分区绘制');for(let i=0;i<=n;i++){const theta=start+(end-start)*i/n,p=[...c];p[a]+=rx*Math.cos(theta);p[b]+=ry*Math.sin(theta);add(p);}}
 else if(kind==='box'){const lo=points[0].map((n,a)=>Math.min(n,points[1][a])),hi=points[0].map((n,a)=>Math.max(n,points[1][a]));for(let k=0;k<3;k++)for(let u=0;u<4;u++){const p=[...lo],q=[...lo],other=[0,1,2].filter(i=>i!==k);other.forEach((i,j)=>p[i]=q[i]=(u>>j&1)?hi[i]:lo[i]);q[k]=hi[k];segment(p,q);}}
 else throw Error('未知图形类型');if(out.length>50000)throw Error('辅助线点数过多，请缩小范围或分段');return out;
}
const surfaceCache=new WeakMap();
export function surfaceColumns(site){const old=surfaceCache.get(site);if(old?.overlay===site.overlay&&old.palette===site.palette.length)return old.columns;const map=new Map();const all=new Map(site.cells);for(const[k,b]of site.overlay)if(b.state<0)all.delete(k);else all.set(k,b);for(const b of all.values()){const key=b.pos[0]+4096*b.pos[2],c=map.get(key)||{ground:null,water:null,top:null,obstacles:[]},type=terrainType(site.palette[b.state].Name);c.top=Math.max(c.top??-1,b.pos[1]);if(type==='ground')c.ground=Math.max(c.ground??-1,b.pos[1]);if(type==='water')c.water=Math.max(c.water??-1,b.pos[1]);if(type==='building'||type==='plant')c.obstacles.push(b);map.set(key,c);}surfaceCache.set(site,{overlay:site.overlay,palette:site.palette.length,columns:map});return map;}
function family(state,available,roles={}){const id=state.Name,stem=id.replace(/_stairs$|_slab$/,'').replace(/_planks$/,'').replace(/bricks$/,'brick'),full=id.endsWith('_stairs')||id.endsWith('_slab')?[stem+'s',stem,stem+'_planks'].find(n=>available.has(n)):id;return{full:roles.full||{...state,Name:full||id},slab:roles.slab||(available.has(stem+'_slab')?{Name:stem+'_slab'}:id.endsWith('_slab')?state:null),stairs:roles.stairs||(available.has(stem+'_stairs')?{Name:stem+'_stairs'}:id.endsWith('_stairs')?state:null)};}
export function curvePiece(point,tangent,{state,available,roles={},voxel='smart',surface='top'}={}){const mat=family(state,available,roles),q=Math.round(point[1]*2)/2,slope=Math.abs(tangent[1])/Math.max(.001,Math.hypot(tangent[0],tangent[2])),stairs=mat.stairs&&((voxel==='stairs')||(voxel==='smart'&&slope>=.25&&slope<=1.05&&Number.isInteger(q))),slab=mat.slab&&(voxel==='slab'||voxel==='smart'&&!stairs),x=Math.floor(point[0]+1e-8),z=Math.floor(point[2]+1e-8);let y,s;
 if(stairs){y=surface==='bottom'?Math.floor(q):Math.ceil(q)-1;const sign=tangent[1]<0?-1:1,dx=tangent[0]*sign,dz=tangent[2]*sign;let facing=Math.abs(dx)>Math.abs(dz)?dx>=0?'east':'west':dz>=0?'south':'north';if(surface==='bottom')facing={north:'south',south:'north',east:'west',west:'east'}[facing];s={...mat.stairs,Properties:{...mat.stairs.Properties,facing,half:surface==='bottom'?'top':'bottom',shape:'straight',waterlogged:'false'}};}
 else if(slab){y=surface==='bottom'?Math.floor(q):Math.floor(q-1e-8);const type=surface==='bottom'?(Number.isInteger(q)?'bottom':'top'):(Number.isInteger(q)?'top':'bottom');s={...mat.slab,Properties:{...mat.slab.Properties,type,waterlogged:'false'}};}
 else{y=surface==='bottom'?Math.round(point[1]):Math.round(point[1])-1;s=mat.full;}
 return{pos:[x,y,z],state:s};
}
function inside(x,y,poly){let result=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])result=!result;}return result;}
export function geometryPlan(site,config,available){config={...constrainSketch(config),available};let guide=sampleFigure(config);if(config.guidesOnly&&(!config.terrain||config.terrain==='none'))return{guide,operations:[],warnings:[],usedRoles:{}};const columns=['surface','supports','grade'].includes(config.terrain)?surfaceColumns(site):null,ops=new Map(),warnings=[],usedRoles={full:0,slab:0,stairs:0};const variants=family(config.state,available,config.roles);if(config.voxel!=='cube'&&!variants.slab&&!variants.stairs)warnings.push('没有匹配的半砖或楼梯，暂用主体方块；可手动指定曲线素材');const add=(pos,state,reason='图形放置')=>{if(pos.some(n=>!Number.isInteger(n)||n<0||n>=4096))throw Error('图形超出当前场景边界');const key=coordKey(...pos),old=ops.get(key);if(old?.state?.Name===state?.Name&&/_slab$/.test(state?.Name)&&old.state.Properties?.type!==state.Properties?.type)state={...state,Properties:{...state.Properties,type:'double'}};ops.set(key,{type:'set',pos,state,reason});};
 if(config.terrain==='surface')guide=guide.map(p=>{const c=columns.get(Math.floor(p[0])+4096*Math.floor(p[2]));return c?.ground!==null&&c?.ground!==undefined?[p[0],c.ground+(config.surface==='bottom'?1:config.voxel==='cube'?2:1.5)+(config.offset||0),p[2]]:p;});
 let samples=guide.map((p,i)=>({p,t:guide[Math.min(guide.length-1,i+1)].map((n,a)=>n-guide[Math.max(0,i-1)][a])}));
 if(config.fill&&['rectangle','circle','ellipse','polygon'].includes(config.kind)){const[a,b]=axes[config.plane||'xz'],poly=guide.map(p=>[p[a],p[b]]),lo=[Math.floor(Math.min(...poly.map(p=>p[0]))),Math.floor(Math.min(...poly.map(p=>p[1])))],hi=[Math.ceil(Math.max(...poly.map(p=>p[0]))),Math.ceil(Math.max(...poly.map(p=>p[1])))];if((hi[0]-lo[0])*(hi[1]-lo[1])>65536)throw Error('填充范围过大，请分区');samples=[];for(let u=lo[0];u<=hi[0];u++)for(let v=lo[1];v<=hi[1];v++)if(inside(u+.5,v+.5,poly)){const p=[...guide[0]];p[a]=u+.5;p[b]=v+.5;samples.push({p,t:[1,0,0]});}}
 if(config.kind==='box'&&config.fill){const lo=config.points[0].map((n,a)=>Math.floor(Math.min(n,config.points[1][a]))),hi=config.points[0].map((n,a)=>Math.floor(Math.max(n,config.points[1][a])));if(hi.reduce((n,v,a)=>n*(v-lo[a]+1),1)>250000)throw Error('体积过大，请分区');for(let y=lo[1];y<=hi[1];y++)for(let x=lo[0];x<=hi[0];x++)for(let z=lo[2];z<=hi[2];z++)add([x,y,z],config.state);return{guide,operations:[...ops.values()],warnings,usedRoles};}
 const width=Math.max(1,Math.min(16,config.width||1)),normalAxis=[0,1,2].find(a=>!(axes[config.plane||'xz']).includes(a)),placed=[];let previous=null;
 for(const sample of samples){for(let u=-(width-1)/2;u<=(width-1)/2;u++){const t=sample.t,p=[...sample.p],a=axes[config.plane||'xz'][0],b=axes[config.plane||'xz'][1],length=Math.hypot(t[a],t[b])||1;p[a]+=-t[b]/length*u;p[b]+=t[a]/length*u;const x=Math.floor(p[0]),z=Math.floor(p[2]),column=columns?.get(x+4096*z);
  if(config.terrain==='surface'){if(column?.ground===null||!column){warnings.push('缺少真实地面的列已略过');continue;}p[1]=column.ground+(config.surface==='bottom'?1:config.voxel==='cube'?2:1.5)+(config.offset||0);if(config.voxel==='smart'&&config.surface!=='bottom'&&Math.abs(t[1])/Math.max(.01,Math.hypot(t[0],t[2]))>=.25)p[1]=Math.ceil(p[1]);}
  const piece=curvePiece(p,t,config),role=/_stairs$/.test(piece.state.Name)?'stairs':/_slab$/.test(piece.state.Name)?'slab':'full';usedRoles[role]++;add(piece.pos,piece.state);placed.push(piece);
  if(previous&&u===-(width-1)/2&&Math.abs(piece.pos[0]-previous.pos[0])===1&&Math.abs(piece.pos[2]-previous.pos[2])===1)add([piece.pos[0],piece.pos[1],previous.pos[2]],piece.state,'曲线连接补格');if(u===-(width-1)/2)previous=piece;
 }}
 if(config.terrain==='supports'){const spacing=Math.max(1,config.spacing||4),seen=new Set();let supportIndex=0;for(const piece of placed){const[x,y,z]=piece.pos,key=x+4096*z;if(seen.has(key))continue;seen.add(key);if(supportIndex++%spacing)continue;const c=columns.get(key);if(c?.ground===null||!c){warnings.push('缺少地面数据，支撑未生成');continue;}if(c.ground>=y){warnings.push('部分地面高于设计面，请抬高或使用整平');continue;}for(let sy=c.ground+1;sy<y;sy++){if(site.at([x,sy,z])){warnings.push('支柱遇到既有方块，已保留');break;}add([x,sy,z],config.roles?.full||config.state,'自动落地支撑');}}}
 if(config.terrain==='grade'){const targets=new Map(placed.map(p=>[p.pos[0]+4096*p.pos[2],p.pos[1]-1]));for(const[key,target]of targets){const x=key%4096,z=Math.floor(key/4096),plan=gradeColumn(site,columns.get(key),x,z,target,config.earthState||{Name:'minecraft:dirt'});for(const op of plan.operations)ops.set(coordKey(...op.pos),op);warnings.push(...plan.warnings);}for(const p of placed)add(p.pos,p.state);}
 if(ops.size>250000)throw Error('本次图形过大，请分段生成');return{guide,operations:[...ops.values()],warnings:[...new Set(warnings)],usedRoles};
}
function gradeColumn(site,c,x,z,target,state){const operations=[],warnings=[];if(c?.ground===null||!c)return{operations,warnings:['缺少真实地面的区域未处理']};if(c.water!==null&&c.water>=Math.min(target,c.ground))return{operations,warnings:['河水与水面保持不变']};const lo=Math.min(c.ground+1,target+1),hi=Math.max(c.ground,target);if(c.obstacles.some(b=>b.pos[1]>=lo&&b.pos[1]<=Math.max(hi,c.ground+1)))return{operations,warnings:['建筑或植被阻挡的列已保留']};for(let y=c.ground;y>target;y--){const b=site.at([x,y,z]);if(b&&terrainType(site.palette[b.state].Name)==='ground')operations.push({type:'set',pos:[x,y,z],state:null,reason:'自动挖方'});}for(let y=c.ground+1;y<=target;y++)operations.push({type:'set',pos:[x,y,z],state,reason:'自动填方'});return{operations,warnings};}
export function terrainPlan(site,{min,max,mode='flatten',y,state={Name:'minecraft:dirt'},radius=1,slopeX=0,slopeZ=0}){if(min.length!==2||max.length!==2||[...min,...max].some(n=>!Number.isInteger(n)||n<0||n>=4096)||min.some((n,a)=>n>max[a])||(max[0]-min[0]+1)*(max[1]-min[1]+1)>65536)throw Error('请选择有效的地形范围，较大范围请分区');const columns=surfaceColumns(site),operations=[],guide=[],warnings=[];let valid=0;for(let x=min[0];x<=max[0];x++)for(let z=min[1];z<=max[1];z++){const c=columns.get(x+4096*z);if(c?.ground===null||!c){warnings.push('无地面数据的列未处理');continue;}valid++;let target=y;if(mode==='smooth'){const values=[];for(let dx=-radius;dx<=radius;dx++)for(let dz=-radius;dz<=radius;dz++){const n=columns.get(x+dx+4096*(z+dz));if(n?.ground!==null&&n?.ground!==undefined&&n.water===null)values.push(n.ground);}values.sort((a,b)=>a-b);target=values.length?values[Math.floor(values.length/2)]:c.ground;}if(mode==='slope')target=y+(x-min[0])*slopeX+(z-min[1])*slopeZ;target=Math.round(target);if(!Number.isInteger(target)||target<0||target>4094)throw Error('目标高度超出场景');const plan=gradeColumn(site,c,x,z,target,state);operations.push(...plan.operations);warnings.push(...plan.warnings);if(x===min[0]||x===max[0]||z===min[1]||z===max[1])guide.push([x+.5,target+1,z+.5]);}if(!valid)throw Error('选区没有真实地面数据，请先导入地形');if(operations.length>250000)throw Error('土方量过大，请分区处理');return{guide,operations,warnings:[...new Set(warnings)],usedRoles:{}};}
