import {sampleSpline} from './spline.js';
import {validateFrame,sketchLocal,sketchWorld,toPlane,fromPlane,dot} from './workplane.js';
import {slopeHeight,slopeMetrics} from './terrain-slope.js';
import {scopeConstruction,assessSupports,assessSurfaceFit} from './construction-scope.js';
import {constrainSketch} from './sketch.js';
import {coordKey,terrainType} from './site.js';
const axes={xz:[0,2],xy:[0,1],yz:[2,1]};
const distance=(a,b)=>Math.hypot(...a.map((n,i)=>n-b[i]));
export function bezier(points,t){let work=points.map(p=>[...p]);while(work.length>1)work=work.slice(0,-1).map((p,i)=>p.map((n,a)=>n*(1-t)+work[i+1][a]*t));return work[0];}
export function sampleFigure(config){if(config.workplane){const f=validateFrame(config.workplane);return sampleFigure({...config,workplane:null,plane:'xz',points:config.points.map(p=>sketchLocal(p,f))}).map(p=>sketchWorld(p,f));}const{kind='bezier',points,plane='xz'}=config;if(!Array.isArray(points)||points.length<2||points.some(p=>p.length!==3||p.some(n=>!Number.isFinite(n))))throw Error('请设置有效的控制点');const density=Math.max(1,Math.min(8,config.sampleDensity??8)),[a,b]=axes[plane]||axes.xz,out=[],add=p=>out.push(p);
 const segment=(p,q)=>{const n=Math.max(1,Math.ceil(distance(p,q)*density));if(n>16384)throw Error('单段过长，请拆分绘制');for(let i=0;i<=n;i++)add(p.map((v,k)=>v+(q[k]-v)*i/n));};
 if(kind==='line')segment(points[0],points.at(-1));
 else if(kind==='spline')return sampleSpline(points,{closed:config.closed===true,density});
 else if(kind==='bezier'){if(points.length<3||points.length>8)throw Error('贝塞尔曲线需要 3–8 个控制点');const length=points.slice(1).reduce((n,p,i)=>n+distance(p,points[i]),0),n=config.sampleCount??Math.min(8192,Math.max(24,Math.ceil(length*density)));if(!Number.isInteger(n)||n<24||n>8192)throw Error('贝塞尔采样数应为 24–8192 的整数');for(let i=0;i<=n;i++)add(bezier(points,i/n));}
 else if(kind==='rectangle'){const p=points[0],q=points[1],corners=[p,[...p],[...q],[...p]];corners[1][a]=q[a];corners[3][b]=q[b];for(let i=0;i<4;i++)segment(corners[i],corners[(i+1)%4]);}
 else if(kind==='polyline'){for(let i=0;i<points.length-1;i++)segment(points[i],points[i+1]);if(config.closed===true){if(points.length<3)throw Error('闭合折线至少需要三个顶点');segment(points.at(-1),points[0]);}}
 else if(kind==='polygon'){for(let i=0;i<points.length;i++)segment(points[i],points[(i+1)%points.length]);}
 else if(['circle','ellipse','arc'].includes(kind)){const c=points[0],radius=Math.hypot(points[1][a]-c[a],points[1][b]-c[b]),rx=kind==='ellipse'?Math.abs(points[1][a]-c[a]):radius,ry=kind==='ellipse'?Math.abs(points[1][b]-c[b]):radius;if(rx<.1||ry<.1)throw Error('半径过小，请拉开控制点');let start=0,end=2*Math.PI;if(kind==='arc'){if(points.length<3)throw Error('圆弧需要圆心、起点和终点');start=Math.atan2(points[1][b]-c[b],points[1][a]-c[a]);end=Math.atan2(points[2][b]-c[b],points[2][a]-c[a]);while(end<=start)end+=2*Math.PI;}const n=Math.max(24,Math.ceil((end-start)*Math.max(rx,ry)*density));if(n>16384)throw Error('图形范围过大，请分区绘制');for(let i=0;i<=n;i++){const theta=start+(end-start)*i/n,p=[...c];p[a]+=rx*Math.cos(theta);p[b]+=ry*Math.sin(theta);add(p);}}
 else if(kind==='box'){const lo=points[0].map((n,a)=>Math.min(n,points[1][a])),hi=points[0].map((n,a)=>Math.max(n,points[1][a]));for(let k=0;k<3;k++)for(let u=0;u<4;u++){const p=[...lo],q=[...lo],other=[0,1,2].filter(i=>i!==k);other.forEach((i,j)=>p[i]=q[i]=(u>>j&1)?hi[i]:lo[i]);q[k]=hi[k];segment(p,q);}}
 else throw Error('未知图形类型');if(out.length>50000)throw Error('辅助线点数过多，请缩小范围或分段');return out;
}
const surfaceCache=new WeakMap();
export function surfaceColumns(site){const old=surfaceCache.get(site);if(old?.overlay===site.overlay&&old.palette===site.palette.length)return old.columns;const map=new Map();const all=new Map(site.cells);for(const[k,b]of site.overlay)if(b.state<0)all.delete(k);else all.set(k,b);for(const b of all.values()){const key=b.pos[0]+4096*b.pos[2],c=map.get(key)||{ground:null,water:null,top:null,obstacles:[]},type=terrainType(site.palette[b.state].Name);c.top=Math.max(c.top??-1,b.pos[1]);if(type==='ground')c.ground=Math.max(c.ground??-1,b.pos[1]);if(type==='water')c.water=Math.max(c.water??-1,b.pos[1]);if(type==='building'||type==='plant')c.obstacles.push(b);map.set(key,c);}surfaceCache.set(site,{overlay:site.overlay,palette:site.palette.length,columns:map});return map;}
function family(state,available,roles={}){const id=state.Name,stem=id.replace(/_stairs$|_slab$/,'').replace(/_planks$/,'').replace(/bricks$/,'brick'),full=id.endsWith('_stairs')||id.endsWith('_slab')?[stem+'s',stem,stem+'_planks'].find(n=>available.has(n)):id;return{full:roles.full||{...state,Name:full||id},slab:roles.slab||(available.has(stem+'_slab')?{Name:stem+'_slab'}:id.endsWith('_slab')?state:null),stairs:roles.stairs||(available.has(stem+'_stairs')?{Name:stem+'_stairs'}:id.endsWith('_stairs')?state:null)};}
export function curvePiece(point,tangent,{state,available,roles={},voxel='smart',surface='top'}={}){const mat=family(state,available,roles),q=Math.round(point[1]*2)/2,slope=Math.abs(tangent[1])/Math.max(.001,Math.hypot(tangent[0],tangent[2])),stairs=mat.stairs&&((voxel==='stairs')||(voxel==='smart'&&slope>=.25&&slope<=1.05&&Number.isInteger(q))),slab=mat.slab&&(voxel==='slab'||voxel==='smart'&&!stairs),x=Math.floor(point[0]+1e-8),z=Math.floor(point[2]+1e-8);let y,s;
 if(stairs){y=surface==='bottom'?Math.floor(q):Math.ceil(q)-1;const sign=tangent[1]<0?-1:1,dx=tangent[0]*sign,dz=tangent[2]*sign;let facing=Math.abs(dx)>Math.abs(dz)?dx>=0?'east':'west':dz>=0?'south':'north';if(surface==='bottom')facing={north:'south',south:'north',east:'west',west:'east'}[facing];s={...mat.stairs,Properties:{...mat.stairs.Properties,facing,half:surface==='bottom'?'top':'bottom',shape:'straight',waterlogged:'false'}};}
 else if(slab){y=surface==='bottom'?Math.floor(q):Math.floor(q-1e-8);const type=surface==='bottom'?(Number.isInteger(q)?'bottom':'top'):(Number.isInteger(q)?'top':'bottom');s={...mat.slab,Properties:{...mat.slab.Properties,type,waterlogged:'false'}};}
 else{y=surface==='bottom'?Math.round(point[1]):Math.round(point[1])-1;s=mat.full;}
 return{pos:[x,y,z],state:s};
}
function inside(x,y,poly){let result=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])result=!result;}return result;}
export function geometryPlan(site,config,available){return assessSurfaceFit(assessSupports(scopeConstruction(geometryUnscoped(site,config,available),config),config),config);}
function geometryUnscoped(site,config,available){config={...constrainSketch(config),available};let guide=sampleFigure(config);if(config.guidesOnly&&(!config.terrain||config.terrain==='none'))return{guide,operations:[],warnings:[],usedRoles:{}};const columns=['surface','supports','grade'].includes(config.terrain)?surfaceColumns(site):null,ops=new Map(),surfaceSkipped=new Map(),warnings=[],usedRoles={full:0,slab:0,stairs:0};const variants=family(config.state,available,config.roles);if(config.voxel!=='cube'&&!variants.slab&&!variants.stairs)warnings.push('没有匹配的半砖或楼梯，暂用主体方块；可手动指定曲线素材');const add=(pos,state,reason='图形放置')=>{if(pos.some(n=>!Number.isInteger(n)||n<0||n>=4096))throw Error('图形超出当前场景边界');const key=coordKey(...pos),old=ops.get(key);if(old?.state?.Name===state?.Name&&/_slab$/.test(state?.Name)&&old.state.Properties?.type!==state.Properties?.type)state={...state,Properties:{...state.Properties,type:'double'}};ops.set(key,{type:'set',pos,state,reason});};
 if(config.terrain==='surface')guide=guide.map(p=>{const c=columns.get(Math.floor(p[0])+4096*Math.floor(p[2]));return c?.ground!==null&&c?.ground!==undefined?[p[0],c.ground+(config.surface==='bottom'?1:config.voxel==='cube'?2:1.5)+(config.offset||0),p[2]]:p;});
 const frame=config.workplane?validateFrame(config.workplane):null,planeAxes=frame?[0,2]:axes[config.plane||'xz'];if(!planeAxes)throw Error('绘制平面无效，请选择工作平面');let samples=guide.map((p,i)=>({p,t:guide[Math.min(guide.length-1,i+1)].map((n,a)=>n-guide[Math.max(0,i-1)][a])}));
 if(config.fill&&config.kind==='spline'&&config.closed){const n=[0,1,2].find(a=>!planeAxes.includes(a)),level=frame?toPlane(guide[0],frame)[2]:guide[0][n];if(guide.some(p=>Math.abs((frame?toPlane(p,frame)[2]:p[n])-level)>1e-6))throw Error('填充需要平面的闭合曲线；请锁定工作平面或只生成路径');}
 if(config.fill&&['polyline','spline'].includes(config.kind)&&!config.closed)throw Error(config.kind==='spline'?'开放曲线不能填充，请闭合路径或取消填充':'开放折线不能填充，请闭合路径或取消填充');
 if(config.fill&&(['rectangle','circle','ellipse','polygon'].includes(config.kind)||['polyline','spline'].includes(config.kind)&&config.closed)){const[a,b]=planeAxes,poly=guide.map(p=>frame?toPlane(p,frame).slice(0,2):[p[a],p[b]]),lo=[Math.floor(Math.min(...poly.map(p=>p[0]))),Math.floor(Math.min(...poly.map(p=>p[1])))],hi=[Math.ceil(Math.max(...poly.map(p=>p[0]))),Math.ceil(Math.max(...poly.map(p=>p[1])))];if((hi[0]-lo[0])*(hi[1]-lo[1])>65536)throw Error('填充范围过大，请分区');samples=[];const step=frame?.5:1;for(let u=lo[0];u<=hi[0];u+=step)for(let v=lo[1];v<=hi[1];v+=step)if(inside(u+step/2,v+step/2,poly)){const p=frame?fromPlane([u+step/2,v+step/2,toPlane(guide[0],frame)[2]],frame):[...guide[0]];if(!frame){p[a]=u+.5;p[b]=v+.5;}samples.push({p,t:[1,0,0]});}}
 if(config.kind==='box'&&config.fill&&frame){const a=sketchLocal(config.points[0],frame),b=sketchLocal(config.points[1],frame),low=a.map((n,i)=>Math.min(n,b[i])),high=a.map((n,i)=>Math.max(n,b[i])),lo=[0,1,2].map(i=>Math.floor(Math.min(...guide.map(p=>p[i])))),hi=[0,1,2].map(i=>Math.ceil(Math.max(...guide.map(p=>p[i]))));if(hi.reduce((n,v,i)=>n*(v-lo[i]+1),1)>250000)throw Error('体积过大，请分区');for(let x=lo[0];x<=hi[0];x++)for(let y=lo[1];y<=hi[1];y++)for(let z=lo[2];z<=hi[2];z++){const q=sketchLocal([x+.5,y+.5,z+.5],frame);if(q.every((n,i)=>n>=low[i]&&n<=high[i]))add([x,y,z],config.state);}return{guide,operations:[...ops.values()],warnings,usedRoles};}
 if(config.kind==='box'&&config.fill){const lo=config.points[0].map((n,a)=>Math.floor(Math.min(n,config.points[1][a]))),hi=config.points[0].map((n,a)=>Math.floor(Math.max(n,config.points[1][a])));if(hi.reduce((n,v,a)=>n*(v-lo[a]+1),1)>250000)throw Error('体积过大，请分区');for(let y=lo[1];y<=hi[1];y++)for(let x=lo[0];x<=hi[0];x++)for(let z=lo[2];z<=hi[2];z++)add([x,y,z],config.state);return{guide,operations:[...ops.values()],warnings,usedRoles};}
 const skipSurface=(x,z,y,reason)=>{const key=x+4096*z;if(!surfaceSkipped.has(key))surfaceSkipped.set(key,{pos:[x,Math.floor(y),z],reason});};
 const width=Math.max(1,Math.min(16,config.width||1)),placed=[];let previous=null,supports=null;
 for(const sample of samples){for(let u=-(width-1)/2;u<=(width-1)/2;u++){const t=sample.t,p=[...sample.p],a=planeAxes[0],b=planeAxes[1],length=Math.hypot(t[a],t[b])||1;if(frame){const tu=dot(t,frame.u),tv=dot(t,frame.v),l=Math.hypot(tu,tv)||1;for(let i=0;i<3;i++)p[i]+=(-tv*frame.u[i]+tu*frame.v[i])/l*u;}else{p[a]+=-t[b]/length*u;p[b]+=t[a]/length*u;}const x=Math.floor(p[0]),z=Math.floor(p[2]),column=columns?.get(x+4096*z);
  if(config.terrain==='surface'){if(column?.ground===null||!column){warnings.push('缺少真实地面的列已略过');skipSurface(x,z,p[1],'missing');continue;}p[1]=column.ground+(config.surface==='bottom'?1:config.voxel==='cube'?2:1.5)+(config.offset||0);if(config.voxel==='smart'&&config.surface!=='bottom'&&Math.abs(t[1])/Math.max(.01,Math.hypot(t[0],t[2]))>=.25)p[1]=Math.ceil(p[1]);}
  const piece=curvePiece(p,t,config),role=/_stairs$/.test(piece.state.Name)?'stairs':/_slab$/.test(piece.state.Name)?'slab':'full';usedRoles[role]++;add(piece.pos,piece.state);placed.push(piece);
  if(previous&&u===-(width-1)/2&&Math.abs(piece.pos[0]-previous.pos[0])===1&&Math.abs(piece.pos[2]-previous.pos[2])===1)add([piece.pos[0],piece.pos[1],previous.pos[2]],piece.state,'曲线连接补格');if(u===-(width-1)/2)previous=piece;
 }}
 if(config.terrain==='supports'){const spacing=Math.max(1,config.spacing||4),seen=new Set(),records=[],buried=new Set();let supportIndex=0;for(const piece of placed){const[x,y,z]=piece.pos,key=x+4096*z;if(seen.has(key))continue;seen.add(key);if(supportIndex++%spacing)continue;const c=columns.get(key),record={x,z,deckY:y,groundY:c?.ground??null,planned:0,status:'grounded'};records.push(record);if(c?.ground===null||!c){record.status='missing';continue;}if(c.ground>=y){record.status='buried';buried.add(key);continue;}let blocked=false;for(let sy=c.ground+1;sy<y;sy++)if(site.at([x,sy,z])){blocked=true;break;}if(blocked){record.status='blocked';continue;}for(let sy=c.ground+1;sy<y;sy++){add([x,sy,z],config.roles?.full||config.state,'自动落地支撑');record.planned++;}}for(const [key,op]of ops)if(buried.has(op.pos[0]+4096*op.pos[2]))ops.delete(key);supports={records};}
 if(config.terrain==='grade'){const road=[...ops.values()],roadMap=new Map(ops),targets=new Map(road.map(p=>[p.pos[0]+4096*p.pos[2],p.pos[1]-1])),skipped=new Set();for(const[key,target]of targets){const x=key%4096,z=Math.floor(key/4096),column=columns.get(key),collision=column?.obstacles.some(b=>{const op=roadMap.get(coordKey(...b.pos));return op&&JSON.stringify(site.palette[b.state])!==JSON.stringify(op.state);});if(collision){skipped.add(key);warnings.push('道路候选遇到建筑或植被，整列已保留');continue;}const plan=gradeColumn(site,column,x,z,target,config.earthState||{Name:'minecraft:dirt'});if(plan.skipped)skipped.add(key);for(const op of plan.operations)ops.set(coordKey(...op.pos),op);warnings.push(...plan.warnings);}for(const [key,op]of ops)if(skipped.has(op.pos[0]+4096*op.pos[2]))ops.delete(key);if(skipped.size)warnings.push('道路在 '+skipped.size+' 列保留水面、障碍或缺失地面，未放置或挖填');}
 if(config.terrain==='surface'){const skipped=new Set();for(const [key,op]of ops){const column=columns.get(op.pos[0]+4096*op.pos[2]),before=site.at(op.pos),type=before?terrainType(site.palette[before.state].Name):null;if(!column||column.ground===null||column.water!==null&&column.water>=column.ground||before&&['building','plant'].includes(type)&&JSON.stringify(site.palette[before.state])!==JSON.stringify(op.state)){ops.delete(key);skipped.add(op.pos[0]+4096*op.pos[2]);skipSurface(op.pos[0],op.pos[2],op.pos[1],!column||column.ground===null?'missing':column.water!==null&&column.water>=column.ground?'water':'obstacle');}}if(skipped.size)warnings.push('贴地路径在 '+skipped.size+' 列保留水面、障碍或缺失地面，候选方块已略过');}
 if(['surface','grade','supports'].includes(config.terrain)){usedRoles.full=usedRoles.slab=usedRoles.stairs=0;for(const op of ops.values())if(op.state)usedRoles[/_stairs$/.test(op.state.Name)?'stairs':/_slab$/.test(op.state.Name)?'slab':'full']++;}
 if(ops.size>250000)throw Error('本次图形过大，请分段生成');return{guide,operations:[...ops.values()],warnings:[...new Set(warnings)],usedRoles,...(supports?{supports}:{}),...(config.terrain==='surface'?{surfaceFit:{records:[...surfaceSkipped.values()]}}:{})};
}
function gradeColumn(site,c,x,z,target,state){const operations=[],warnings=[];if(c?.ground===null||!c)return{operations,skipped:true,warnings:['缺少真实地面的区域未处理']};if(c.water!==null&&c.water>=Math.min(target,c.ground))return{operations,skipped:true,warnings:['河水与水面保持不变']};const lo=Math.min(c.ground+1,target+1),hi=Math.max(c.ground,target);if(c.obstacles.some(b=>b.pos[1]>=lo&&b.pos[1]<=Math.max(hi,c.ground+1)))return{operations,skipped:true,warnings:['建筑或植被阻挡的列已保留']};for(let y=c.ground;y>target;y--){const b=site.at([x,y,z]);if(b&&terrainType(site.palette[b.state].Name)==='ground')operations.push({type:'set',pos:[x,y,z],state:null,reason:'自动挖方'});}for(let y=c.ground+1;y<=target;y++)operations.push({type:'set',pos:[x,y,z],state,reason:'自动填方'});return{operations,warnings};}
export function terrainPlan(site,config){return scopeConstruction(terrainUnscoped(site,config),config);}
function terrainUnscoped(site,{min,max,mode='flatten',y,state={Name:'minecraft:dirt'},radius=1,slopeX=0,slopeZ=0,slopePoints=null}){if(min.length!==2||max.length!==2||[...min,...max].some(n=>!Number.isInteger(n)||n<0||n>=4096)||min.some((n,a)=>n>max[a])||(max[0]-min[0]+1)*(max[1]-min[1]+1)>65536)throw Error('请选择有效的地形范围，较大范围请分区');if(mode==='slope'&&slopePoints)slopeMetrics(slopePoints);const columns=surfaceColumns(site),operations=[],guide=[],warnings=[];let valid=0;for(let x=min[0];x<=max[0];x++)for(let z=min[1];z<=max[1];z++){const c=columns.get(x+4096*z);if(c?.ground===null||!c){warnings.push('无地面数据的列未处理');continue;}valid++;let target=y;if(mode==='smooth'){const values=[];for(let dx=-radius;dx<=radius;dx++)for(let dz=-radius;dz<=radius;dz++){const n=columns.get(x+dx+4096*(z+dz));if(n?.ground!==null&&n?.ground!==undefined&&n.water===null)values.push(n.ground);}values.sort((a,b)=>a-b);target=values.length?values[Math.floor(values.length/2)]:c.ground;}if(mode==='slope')target=slopePoints?slopeHeight(slopePoints,x,z):y+(x-min[0])*slopeX+(z-min[1])*slopeZ;target=Math.round(target);if(!Number.isInteger(target)||target<0||target>4094)throw Error('目标高度超出场景');const plan=gradeColumn(site,c,x,z,target,state);operations.push(...plan.operations);warnings.push(...plan.warnings);if(x===min[0]||x===max[0]||z===min[1]||z===max[1])guide.push([x+.5,target+1,z+.5]);}if(!valid)throw Error('选区没有真实地面数据，请先导入地形');if(operations.length>250000)throw Error('土方量过大，请分区处理');return{guide,operations,warnings:[...new Set(warnings)],usedRoles:{}};}
