import {profileFrame,sketchLocal,sketchWorld,validateFrame} from './workplane.js';
import {closedProfiles} from './sketch-profiles.js';
import {affectedGeneration} from './generation-order.js';
import {componentCell,sameComponentCell} from './component-state.js';
import {instancePose,instancePoint,composeInstancePose} from './instance-transform.js';
import {registerLinkedInstance,componentUpdatePlan,makeUniqueComponentPlan} from './components.js';
import {regenerateObjects,detachedGeneration} from './generation.js';
import {coordKey,coords} from './site.js';
import {selection,insertOperations,rotateState} from './studio.js';
import {geometryPlan,surfaceColumns} from './construction.js';
import {featurePlan} from './features.js';
const bounds=points=>({min:[0,1,2].map(a=>points.reduce((v,p)=>Math.min(v,p[a]),Infinity)),max:[0,1,2].map(a=>points.reduce((v,p)=>Math.max(v,p[a]),-Infinity))});
const integer=(n,name,min=-4095,max=4095)=>{if(!Number.isInteger(n)||n<min||n>max)throw Error(name+'需要 '+min+'–'+max+' 的整数');return n;};
export function selectedObjects(site,c,{allowLocked=false}={}){if(c.objectIds?.length){const items=c.objectIds.map(id=>site.design.objects.find(o=>o.id===id));if(items.some(o=>!o))throw Error('选择对象已变化，请重新选择');if(!allowLocked&&items.some(o=>o.locked))throw Error('选择包含锁定对象');return items;}if(!c.selection)throw Error('先选择对象或区域');const {min,max,members,regions}=c.selection,p=selection(site,min,max,{keys:members,regions});if(!p.blocks.length)throw Error('选择没有方块');return[{id:null,name:'选区',min,max,cells:p.blocks.map(b=>coordKey(...b.pos.map((n,a)=>n+min[a])))}];}
const capture=(site,o)=>selection(site,o.min,o.max,{keys:o.cells});
function shiftedObject(o,ops){const points=ops.filter(o=>o.state).map(o=>o.pos);return{...structuredClone(o),...bounds(points),cells:[...new Set(points.map(p=>coordKey(...p)))]};}
function offsetFrame(points,reference){const f=profileFrame(points,'auto',reference),a=f.u,b=f.v,cross=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];if(cross.reduce((sum,n,i)=>sum+n*f.normal[i],0)<0)f.v=f.v.map(n=>-n);return validateFrame(f);}
function offsetContour(points,plane,d){const axes=({xz:[0,2],xy:[0,1],yz:[2,1]})[plane],[u,v]=axes,raw=points.filter((p,i)=>!i||Math.hypot(p[u]-points[i-1][u],p[v]-points[i-1][v])>1e-8).map(p=>[...p]);if(raw.length>1&&Math.hypot(raw[0][u]-raw.at(-1)[u],raw[0][v]-raw.at(-1)[v])<1e-8)raw.pop();const p=raw.filter((b,i)=>{const a=raw[(i+raw.length-1)%raw.length],c=raw[(i+1)%raw.length],ab=[b[u]-a[u],b[v]-a[v]],bc=[c[u]-b[u],c[v]-b[v]],length=Math.hypot(...ab)*Math.hypot(...bc);return !length||Math.abs(ab[0]*bc[1]-ab[1]*bc[0])>1e-9*length||ab[0]*bc[0]+ab[1]*bc[1]<=0;});if(p.length<3)throw Error('轮廓没有有效面积');const area=p.reduce((s,q,i)=>s+q[u]*p[(i+1)%p.length][v]-p[(i+1)%p.length][u]*q[v],0);if(Math.abs(area)<1e-6)throw Error('轮廓没有面积');const sign=Math.sign(area),out=[];for(let i=0;i<p.length;i++){const a=p[(i+p.length-1)%p.length],b=p[i],c=p[(i+1)%p.length],normal=(a,b)=>{const dx=b[u]-a[u],dy=b[v]-a[v],l=Math.hypot(dx,dy)||1;return[sign*dy/l,-sign*dx/l];},n1=normal(a,b),n2=normal(b,c),den=1+n1[0]*n2[0]+n1[1]*n2[1];if(den<.02)throw Error('轮廓含尖锐折返，请分段偏移');const q=[...b];q[u]+=d*(n1[0]+n2[0])/den;q[v]+=d*(n1[1]+n2[1])/den;if(Math.hypot(q[u]-b[u],q[v]-b[v])>Math.abs(d)*8)throw Error('角点偏移过大，请减小距离');out.push(q);}if(d<0){for(let i=0;i<p.length;i++){const j=(i+1)%p.length,a=[p[j][u]-p[i][u],p[j][v]-p[i][v]],b=[out[j][u]-out[i][u],out[j][v]-out[i][v]];if(a[0]*b[0]+a[1]*b[1]<=1e-10*(a[0]*a[0]+a[1]*a[1]))throw Error('向内偏移使轮廓边界消失或反向，请减小距离');}const original=bounds(p),next=bounds(out);if(next.max[u]-next.min[u]>=original.max[u]-original.min[u]||next.max[v]-next.min[v]>=original.max[v]-original.min[v])throw Error('向内偏移超过轮廓宽度');}return out;}
export function designerPlan(site,c,available=new Set()){
 const operation=c.operation,design=structuredClone(site.design),warnings=[],guide=[],operations=[];
 const finish=()=>({operations,design,guide,warnings:[...new Set(warnings)],usedRoles:{}}),add=op=>{if(op.pos.some(n=>!Number.isInteger(n)||n<0||n>=4096))throw Error('结果超出画布，请调整间距或位置');operations.push(op);if(operations.length>1000000)throw Error('本次操作过大，请分批');};
 if(operation==='offset'){const saved=site.design.guides?.find(g=>g.id===c.guideId);const profile=saved&&closedProfiles([saved])[0];if(!profile)throw Error('请选择闭合且共面的轮廓');const d=Number(c.distance);if(!Number.isFinite(d)||!d||Math.abs(d)>128)throw Error('偏移距离应为非零的 -128–128 格');const frame=offsetFrame(profile.points,saved.recipe.workplane),points=offsetContour(profile.points.map(p=>sketchLocal(p,frame)),'xz',d).map(p=>sketchWorld(p,frame)),config={...saved.recipe,kind:'polygon',plane:'custom',workplane:frame,planeLock:true,snapApplied:true,points,guidesOnly:!!c.guidesOnly,state:c.state||saved.recipe.state,fill:false};const plan=geometryPlan(site,config,available);if(!c.guidesOnly)operations.push(...plan.operations);guide.push(...plan.guide);warnings.push(...plan.warnings,'复杂凹轮廓偏移可能自交，请检查辅助线');design.guides||=[];design.guides.push({id:crypto.randomUUID(),name:'偏移轮廓',points:plan.guide,recipe:config});return finish();}
 const objects=selectedObjects(site,c),snapshots=objects.map(o=>capture(site,o)),axis=({x:0,y:1,z:2})[c.axis||'x'];if(axis===undefined)throw Error('无效方向');
 const changed=new Set(),produced=[];const removeObject=o=>{if(o.id){design.objects=design.objects.filter(v=>v.id!==o.id);delete design.animations[o.id];}};
 const eraseObject=(o,p)=>{for(const b of p.blocks){const pos=b.pos.map((n,a)=>n+o.min[a]);changed.add(coordKey(...pos));add({type:'set',pos,state:null,reason:'设计变换原位置'});}};
 function place(o,p,at,{turn=0,mirror=false,move=false,instance=false}={}){if(p.blocks.some(b=>b.nbt)&&(turn||mirror))throw Error('带方块实体的结构可平移，旋转镜像请用原生蓝图');const ops=insertOperations(p,at,{turn,mirror}).map(op=>({...op,nbt:op.nbt??null}));produced.push(...ops);const clone=shiftedObject(o,ops);clone.id=move&&o.id?o.id:crypto.randomUUID();clone.name=move?o.name:o.name+' · 副本';if(instance){registerLinkedInstance(site,design,o,p,clone,at,{turn,mirror});}else if(!move){delete clone.instanceOf;delete clone.instanceTransform;delete clone.instancePose;delete clone.componentRecords;delete clone.componentRevision;}if(move&&o.instancePose){const outer=instancePose(p.size,at,turn,mirror);clone.instancePose=composeInstancePose(o.instancePose,pos=>instancePoint(pos.map((n,a)=>n-o.min[a]),outer),turn,mirror);clone.instanceTransform={turn:clone.instancePose.turn,mirror:clone.instancePose.mirror};const mapping=new Map(p.blocks.map(block=>[coordKey(...instancePoint(block.pos,outer)),coordKey(...block.pos.map((n,a)=>n+o.min[a]))])),records=new Map((o.componentRecords||[]).map(r=>[coordKey(...r.pos),r]));clone.componentRecords=ops.map(op=>{const sourceKey=mapping.get(coordKey(...op.pos)),old=records.get(sourceKey);return{pos:op.pos,before:o.cells.includes(coordKey(...op.pos))?null:componentCell(site,op.pos),after:{state:op.state,nbt:op.nbt||null},manual:!!old&&(old.manual||!sameComponentCell(componentCell(site,coords(sourceKey)),old.after))};});}if(move&&o.id)design.objects=design.objects.filter(v=>v.id!==o.id);design.objects.push(clone);const animation=site.design.animations[o.id];if(animation&&move&&!turn&&!mirror){const delta=at.map((n,a)=>n-o.min[a]),copy=structuredClone(animation);for(const k of ['min','max','center'])if(copy[k])copy[k]=copy[k].map((n,a)=>n+delta[a]);design.animations[clone.id]=copy;}else if(move&&animation){delete design.animations[clone.id];warnings.push('装置运动由 Create 数据重新识别');}return clone;}
 if(['align','distribute'].includes(operation)){if(objects.length<2)throw Error('请用 Shift 选择至少两个对象');const indices=objects.map((_,i)=>i).sort((a,b)=>objects[a].min[axis]-objects[b].min[axis]),edge=c.edge||'min',value=o=>edge==='max'?o.max[axis]+1:edge==='center'?(o.min[axis]+o.max[axis]+1)/2:o.min[axis],reference=objects[c.reference==='last'?objects.length-1:0],values=new Map();if(operation==='align')for(const i of indices)values.set(i,value(reference));else{if(objects.length<3)throw Error('均匀分布至少需要三个对象');const first=objects[indices[0]],last=objects[indices.at(-1)];if(c.distribution==='centers'){const lo=value({...first}),hi=value({...last});indices.forEach((id,i)=>values.set(id,lo+(hi-lo)*i/(indices.length-1)));}else{const total=objects.reduce((n,o)=>n+o.max[axis]-o.min[axis]+1,0),gap=(last.max[axis]+1-first.min[axis]-total)/(objects.length-1);if(gap<0)warnings.push('对象跨度不足，会形成重叠');let at=first.min[axis];for(const i of indices){values.set(i,at);at+=objects[i].max[axis]-objects[i].min[axis]+1+gap;}}}objects.forEach((o,i)=>eraseObject(o,snapshots[i]));objects.forEach((o,i)=>{const current=operation==='distribute'&&c.distribution!=='centers'?o.min[axis]:value(o),delta=Math.round(values.get(i)-current);if(values.get(i)-current!==delta)warnings.push('中心或间隙已吸附到整数方块');place(o,snapshots[i],o.min.map((n,a)=>n+(a===axis?delta:0)),{move:true});});}
 else if(['array','pathArray','radialArray','mirror','instance'].includes(operation)){const p=selection(site,c.selection?.min||bounds(objects.flatMap(o=>o.cells.map(coords))).min,c.selection?.max||bounds(objects.flatMap(o=>o.cells.map(coords))).max,{keys:objects.flatMap(o=>o.cells)}),combined={id:objects.length===1?objects[0].id:null,name:objects.length===1?objects[0].name:'组合选区',...bounds(objects.flatMap(o=>o.cells.map(coords)))};const count=integer(Number(c.count??3),'数量',1,100);if(operation==='mirror'){if(axis===1)throw Error('当前镜像支持 X / Z，保持门与楼梯上下关系');const plane=Number(c.plane??combined.max[axis]+2);if(!Number.isFinite(plane)||!Number.isInteger(plane*2))throw Error('镜像平面支持整格或半格');const at=[...combined.min];at[axis]=Math.round(2*plane-combined.max[axis]-1);place(combined,p,at,{mirror:true,turn:axis===2?2:0});}
 else if(operation==='array'||operation==='instance'){if(count<2)throw Error('数量至少为 2（包含原件）');if(operation==='instance'&&(objects.length!==1||!objects[0].id))throw Error('关联实例请先将选区建立为单个对象');const step=(c.step||[6,0,0]).map((n,a)=>integer(Number(n),'间距 '+a));if(step.every(n=>!n))throw Error('阵列间距不能全部为零');for(let i=1;i<count;i++)place(combined,p,combined.min.map((n,a)=>n+step[a]*i),{instance:operation==='instance'});}
 else if(operation==='radialArray'){const center=c.center||[combined.min[0],combined.min[1],combined.min[2]],radius=Number(c.radius??12),angle=Number(c.angle??360);if(center.length!==3||center.some(n=>!Number.isFinite(n))||!Number.isFinite(radius)||radius<1||radius>1024||!Number.isFinite(angle)||Math.abs(angle)>360)throw Error('请设置有效圆心、半径和角度');for(let i=0;i<count;i++){const t=(c.startAngle||0)+angle*i/(Math.abs(angle)===360?count:Math.max(1,count-1)),r=t*Math.PI/180;place(combined,p,[Math.round(center[0]+Math.cos(r)*radius),Math.round(center[1]),Math.round(center[2]+Math.sin(r)*radius)],{turn:c.follow?((Math.round(t/90)+1)%4+4)%4:0});}if(c.follow)warnings.push('方块朝向按 90° 吸附，圆心参数是构件放置锚点');}
 else{const path=c.path||site.design.guides?.find(g=>g.id===c.guideId)?.points;if(!path?.length)throw Error('请先选择辅助路径');const spacing=Number(c.spacing??6);if(!Number.isFinite(spacing)||spacing<1||spacing>1024)throw Error('路径间距应为 1–1024 格');let next=0,travel=0,placed=0;for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],length=Math.hypot(...b.map((n,k)=>n-a[k]));if(!length)continue;while(next<=travel+length+1e-8){const t=(next-travel)/length,at=a.map((n,k)=>Math.round(n+(b[k]-n)*t)),turn=c.follow?((Math.round(Math.atan2(b[0]-a[0],-(b[2]-a[2]))/(Math.PI/2))%4)+4)%4:0;place(combined,p,at,{turn});next+=spacing;if(++placed>=count)break;}travel+=length;if(placed>=count)break;}warnings.push('沿路径朝向按 90° 吸附；路径不足时减少实例数量');}}
 else if(operation==='pushpull'){if(objects.length!==1)throw Error('推拉一次选择一个对象或区域');const o=objects[0],p=snapshots[0],distance=integer(Number(c.distance??3),'推拉距离',-128,128),positive=c.face!=='min',level=positive?p.size[axis]-1:0,face=p.blocks.filter(b=>b.pos[axis]===level);if(!distance)throw Error('距离不能为零');if(face.some(b=>b.nbt))throw Error('边界含方块实体，请逐块调整，避免复制设备数据');if(distance>0){for(const b of face)for(let i=1;i<=distance;i++){const pos=b.pos.map((n,a)=>n+o.min[a]+(a===axis?(positive?i:-i):0));produced.push({type:'set',pos,state:b.state,reason:'边界推拉'});}const clone=shiftedObject(o,[...p.blocks.map(b=>({pos:b.pos.map((n,a)=>n+o.min[a]),state:b.state})),...produced]);if(o.id)design.objects=design.objects.filter(v=>v.id!==o.id);clone.id=o.id||crypto.randomUUID();design.objects.push(clone);}else{const remove=p.blocks.filter(b=>positive?b.pos[axis]>level+distance:b.pos[axis]<-distance);for(const b of remove)add({type:'set',pos:b.pos.map((n,a)=>n+o.min[a]),state:null,reason:'边界缩短'});warnings.push('缩短只移除选择内方块，门窗与其余细节保持原位置');}}
 else if(operation==='boolean'){if(objects.length!==2)throw Error('布尔操作需要两个对象：先选主体，再 Shift 选工具体');const[a,b]=objects,keysA=new Set(a.cells),keysB=new Set(b.cells),mode=c.mode||'subtract',keys=mode==='union'?new Set([...keysA,...keysB]):mode==='intersect'?new Set([...keysA].filter(k=>keysB.has(k))):new Set([...keysA].filter(k=>!keysB.has(k)));if(!['union','intersect','subtract'].includes(mode))throw Error('未知布尔操作');for(const k of keysA)if(!keys.has(k))add({type:'set',pos:coords(k),state:null,reason:'布尔 '+mode});if(c.consumeTool&&mode!=='union')for(const k of keysB)if(!keys.has(k))add({type:'set',pos:coords(k),state:null,reason:'移除工具体'});removeObject(a);if(mode==='union'||c.consumeTool)removeObject(b);if(keys.size)design.objects.push({id:crypto.randomUUID(),name:a.name+' · 布尔',...bounds([...keys].map(coords)),cells:[...keys],kind:'boolean'});}
 else if(operation==='makeUniqueInstance'){if(objects.length!==1)throw Error('请选择一份实例');return makeUniqueComponentPlan(site,objects[0]);}
 else if(operation==='syncInstances'||operation==='detachInstance'){if(objects.length!==1||!objects[0].instanceOf)throw Error('请先选择一个关联实例');const source=objects[0];if(operation==='syncInstances')return componentUpdatePlan(site,source,{manualStrategy:c.overlap==='overwrite'?'overwrite':'preserve',expandSelection:c.expandSource?c.selection:null});const o=design.objects.find(o=>o.id===source.id);delete o.instanceOf;delete o.instanceTransform;delete o.instancePose;delete o.componentRecords;delete o.componentRevision;}
 else if(operation==='editFeature'){if(objects.length!==1||objects[0].kind!=='feature'||!objects[0].recipe)throw Error('选择一个由拉伸或放样创建的对象');const o=objects[0],config={...o.recipe,...c.parameters};const downstream=o.guideId?affectedGeneration(site.design,o.guideId,detachedGeneration).objects:[];return regenerateObjects(site,[o,...downstream.filter(v=>v.id!==o.id)],{manualStrategy:c.overlap==='overwrite'?'overwrite':'preserve',overrides:{[o.id]:config},available});}
 else throw Error('未知设计工具');
 const sourceKeys=new Set(operations.filter(o=>!o.state).map(o=>coordKey(...o.pos))),destinations=new Map();for(const op of produced){const k=coordKey(...op.pos);if(destinations.has(k))warnings.push('生成构件之间存在重叠');const existing=site.at(op.pos);if(existing&&!sourceKeys.has(k)&&c.overlap!=='overwrite'){throw Error('目标已有方块，请调整位置或选择覆盖');}destinations.set(k,op);}
 for(const op of destinations.values())add(op);
 const remaining=new Map();for(const op of operations)remaining.set(coordKey(...op.pos),op.state);design.objects=design.objects.map(o=>{const cells=(o.cells||[]).filter(k=>!remaining.has(k)||remaining.get(k));if(!cells.length)return null;return{...o,...bounds(cells.map(coords)),cells};}).filter(Boolean);
 return finish();
}
export function designInspection(site,c){const objects=selectedObjects(site,c,{allowLocked:true}),keys=[...new Set(objects.flatMap(o=>o.cells))],materials={},layers={},unsupported=[],collisions=[],actual=[];let unsupportedCount=0,collisionsCount=0;const columns=surfaceColumns(site);for(const k of keys){const b=site.at(coords(k));if(!b)continue;actual.push(b.pos);const state=site.palette[b.state];materials[state.Name]=(materials[state.Name]||0)+1;(layers[b.pos[1]]||= {total:0,materials:{}}).total++;layers[b.pos[1]].materials[state.Name]=(layers[b.pos[1]].materials[state.Name]||0)+1;const below=[b.pos[0],b.pos[1]-1,b.pos[2]];if(b.pos[1]>0&&!site.at(below)){unsupportedCount++;if(unsupported.length<200)unsupported.push(b.pos);}const original=site.at(b.pos,true);if(original&&site.overlay.has(k)){collisionsCount++;if(collisions.length<200)collisions.push({pos:b.pos,original:site.palette[original.state].Name});}}if(!actual.length)throw Error('对象中已没有方块，请重新选择');const points=actual,box=bounds(points),land=[];for(const [x,z]of points.map(p=>[p[0],p[2]])){const col=columns.get(x+4096*z);if(col?.ground!==null&&col?.ground!==undefined)land.push(col.ground);}return{...box,size:box.max.map((n,a)=>n-box.min[a]+1),blockCount:Object.values(materials).reduce((a,b)=>a+b,0),materials,layers,unsupported,unsupportedCount,collisions,collisionsCount,terrain:land.length?{min:land.reduce((a,b)=>Math.min(a,b),Infinity),max:land.reduce((a,b)=>Math.max(a,b),-Infinity)}:null,notes:['悬空标记表示正下方没有方块，横梁和拱券可能正常；不模拟力学','碰撞列表指原始场地被改动的位置，未知地面保持未知']};}
