export function desktopUI({info,$,task,openFile,call,imported,refresh,render,markDirty,notice,clearTextures,checkpoint}){
 document.querySelector('.brand em').textContent='本地';document.title='CraftStudio · 本地建筑设计';document.querySelector('.foot-right').textContent='本地服务 · SQLite 工程库 · v'+info.version;$('library-dialog').querySelector('.muted').textContent='工程和版本保存在本机 SQLite 数据库；浏览器工程库首次连接时会迁入，原数据保留。';
 const dialog=document.createElement('dialog');dialog.id='desktop-dialog';dialog.className='cad-dialog';dialog.innerHTML=`<div class="dialog-header"><h2>从 Minecraft 实例读取</h2><button id="desktop-close">关闭</button></div><div class="cad-dialog-body"><p class="muted">按你选择的蓝图、区域和资源文件读取，不修改原存档。</p><label>实例<select id="desktop-instance"></select></label><div class="row"><button data-desktop-tab="schematic">蓝图</button><button data-desktop-tab="world">真实地形区域</button><button data-desktop-tab="resources">模型与材质</button></div><section id="desktop-schematic"><label>蓝图<select id="desktop-schematic-file"></select></label><button id="desktop-read-schematic" class="primary">读取到设计器</button></section><section id="desktop-world" hidden><label>存档<select id="desktop-world-file"></select></label><label>维度<select id="desktop-dimension"></select></label><div class="row"><label>起点 X<input id="desktop-min-x" type="number" value="0"></label><label>Y<input id="desktop-min-y" type="number" value="0"></label><label>Z<input id="desktop-min-z" type="number" value="0"></label></div><div class="row"><label>终点 X<input id="desktop-max-x" type="number" value="31"></label><label>Y<input id="desktop-max-y" type="number" value="127"></label><label>Z<input id="desktop-max-z" type="number" value="31"></label></div><button id="desktop-read-world" class="primary">读取这个真实区域</button></section><section id="desktop-resources" hidden><p class="small">只导入勾选的文件；可先选原版，再按需补充模组和材质包。</p><div id="desktop-resource-list"></div><button id="desktop-read-resources" class="primary">导入已勾选资源</button></section><p id="desktop-report" class="small"></p><details><summary>读取旧版本地工程库</summary><select id="desktop-legacy"></select><button id="desktop-read-legacy">读取旧工程</button></details></div>`;document.body.append(dialog);
 const button=document.createElement('button');button.id='desktop-files-open';button.className='full';button.textContent='从 Minecraft 实例读取';button.onclick=()=>task(async()=>{dialog.showModal();if(!$('desktop-instance').options.length){$('desktop-report').textContent='没有发现 Minecraft 实例；仍可手动选择文件。可配置 CRAFTSTUDIO_MINECRAFT_HOME。';return;}await loadFiles();const legacy=await fetch((info.baseUrl||'')+'/api/library').then(r=>r.json());$('desktop-legacy').replaceChildren(...(legacy.items||[]).map(p=>option(p.id,p.title)));});document.querySelector('#cad-file-dialog .cad-dialog-body').prepend(button);
 function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
 $('desktop-instance').replaceChildren(...info.instances.map(i=>option(i.id,i.id+' · '+i.loader)));let files=null;
 async function json(url,body){const r=await fetch((info.baseUrl||'')+url,body?{method:'POST',headers:{'Content-Type':'application/json','X-CraftStudio-Token':info.token},body:JSON.stringify(body)}:{}),value=await r.json();if(!r.ok||value.error)throw Error(value.error||'读取失败');return value;}
 async function loadFiles(){files=await json('/api/desktop/files?instance='+encodeURIComponent($('desktop-instance').value));$('desktop-schematic-file').replaceChildren(...files.schematics.map(p=>option(p.path,p.name)));$('desktop-world-file').replaceChildren(...files.worlds.map(w=>option(w.id,w.id)));dimensions();$('desktop-resource-list').replaceChildren(...files.resources.map((r,i)=>{const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.dataset.resource=i;label.append(input,document.createTextNode(({vanilla:'原版',mod:'模组',resourcepack:'材质包'})[r.kind]+' · '+r.name));return label;}));$('desktop-report').textContent=files.schematics.length+' 份蓝图 · '+files.worlds.length+' 个存档 · '+files.resources.length+' 个可选资源文件';}
 function dimensions(){const world=files?.worlds.find(w=>w.id===$('desktop-world-file').value);$('desktop-dimension').replaceChildren(...(world?.dimensions||[]).map(name=>option(name,name)));}
 function fileUrl(r){return(info.baseUrl||'')+'/api/desktop/file?'+new URLSearchParams({instance:$('desktop-instance').value,kind:r.kind,path:r.path});}
 $('desktop-close').onclick=()=>dialog.close();$('desktop-instance').onchange=()=>task(loadFiles);$('desktop-world-file').onchange=dimensions;for(const tab of dialog.querySelectorAll('[data-desktop-tab]'))tab.onclick=()=>{for(const name of ['schematic','world','resources'])$('desktop-'+name).hidden=name!==tab.dataset.desktopTab;};
 $('desktop-read-schematic').onclick=()=>task(async()=>{const row=files.schematics.find(r=>r.path===$('desktop-schematic-file').value);if(!row)throw Error('请选择蓝图');const response=await fetch(fileUrl({...row,kind:'schematic'}));if(!response.ok)throw Error('蓝图读取失败');await openFile(new File([await response.arrayBuffer()],row.name));dialog.close();});
 $('desktop-read-world').onclick=()=>task(async()=>{if(!$('desktop-world-file').value||!$('desktop-dimension').value)throw Error('请选择存档和维度');await checkpoint();const p=await json('/api/desktop/world',{instance:$('desktop-instance').value,world:$('desktop-world-file').value,dimension:$('desktop-dimension').value,min:['x','y','z'].map(a=>Number($('desktop-min-'+a).value)),max:['x','y','z'].map(a=>Number($('desktop-max-'+a).value))}),bytes=new TextEncoder().encode(JSON.stringify(p));await imported(await call('import',{name:p.name+'.json',bytes:bytes.buffer},[bytes.buffer]));dialog.close();notice('已读取真实地形区域，原存档保持不变');},'读取所选存档区域…');
 $('desktop-read-resources').onclick=()=>task(async()=>{const chosen=[...$('desktop-resource-list').querySelectorAll('input:checked')].map(n=>files.resources[Number(n.dataset.resource)]);if(!chosen.length)throw Error('请勾选需要的原版、模组或材质包');const selected=[];for(const r of chosen){const response=await fetch(fileUrl(r));if(!response.ok)throw Error('读取失败：'+r.name);selected.push({name:r.name,bytes:await response.arrayBuffer()});}refresh(await call('resources',{files:selected},selected.map(f=>f.bytes)));clearTextures();await render();markDirty();dialog.close();notice('已导入所选的 '+selected.length+' 个资源文件');});
 $('desktop-read-legacy').onclick=()=>task(async()=>{if(!$('desktop-legacy').value)throw Error('旧工程库没有可读取的工程');const r=await fetch((info.baseUrl||'')+'/api/library/export?id='+encodeURIComponent($('desktop-legacy').value));if(!r.ok)throw Error('旧工程读取失败');await openFile(new File([await r.arrayBuffer()],'旧工程.craft.json'));dialog.close();});
 return{dialog};
}
