import {textEditing} from './keyboard-context.js';
import {TransformControls} from '../../web/vendor/TransformControls.js';
export function directEdit({THREE,$,scene,getCamera,renderer,navigation,requestRender,call,refresh,render,markDirty,policy,studio,hasSelection,notice,cast,hitCell}){
 const parent=new THREE.Group(),proxy=new THREE.Group(),offset=new THREE.Group();parent.add(proxy);proxy.add(offset);scene.add(parent);const control=new TransformControls(getCamera(),renderer.domElement);control.setTranslationSnap(1);control.setRotationSnap(Math.PI/2);control.setSpace('local');control.setSize(.85);scene.add(control.getHelper());let active=null,ghost=null,loading=false,applying=false,clipboard=null,checkToken=0,checkTimer=null,session=0; 
 const bar=document.createElement('div');bar.id='direct-edit-bar';bar.hidden=true;bar.innerHTML=`<strong id="direct-edit-label"></strong><span id="direct-edit-hint"></span><div class="direct-fields"><label>ΔX<input id="direct-dx" type="number" value="0" step="1"></label><label>ΔY<input id="direct-dy" type="number" value="0" step="1"></label><label>ΔZ<input id="direct-dz" type="number" value="0" step="1"></label><label id="direct-overlap-label" hidden>重叠处理<select id="direct-overlap"><option value="empty">避开已有方块</option><option value="overwrite">覆盖目标方块</option><option value="replace">只替换已有方块</option></select></label><button id="direct-quarter">转 90°</button><button id="direct-apply" class="primary">确定 ↵</button><button id="direct-cancel">取消 Esc</button></div>`;$('scene').append(bar);
 function dispose(){if(ghost){ghost.traverse(m=>{if(m.isMesh){m.geometry.dispose();m.material.dispose();}});offset.remove(ghost);ghost=null;}}
 let pointer=null,navigationHeld=false,copying=null,copyToken=0;
 window.addEventListener('keydown',e=>{if(e.code==='Space'&&!textEditing(document.activeElement))navigationHeld=true;});window.addEventListener('keyup',e=>{if(e.code==='Space')navigationHeld=false;});window.addEventListener('blur',()=>navigationHeld=false);
 function pointerAnchor(e){const hit=cast?.(e);if(hit&&!hit.object.userData.readOnly)return hitCell(hit,true).pos;const rect=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2),getCamera());const y=active?.min?.[1]??studio.getSelection().min[1],point=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-y),new THREE.Vector3());return point?.toArray().map(Math.floor)||null;}
 function locate(e){if(!active?.floating||applying)return;const at=pointerAnchor(e);if(!at||at.some(n=>n<0||n>=4096))return;const v=values();proxy.position.set(...at.map((n,a)=>n+v.extent[a]/2-parent.position.getComponent(a)));update();}
 renderer.domElement.addEventListener('pointermove',e=>{pointer={clientX:e.clientX,clientY:e.clientY};if(!e.buttons&&!e.altKey&&!navigationHeld)locate(e);});
 renderer.domElement.addEventListener('pointerdown',e=>{if(!active?.floating||e.button!==0||e.altKey||navigationHeld||applying)return;locate(e);active.floating=false;control.attach(proxy);update();e.preventDefault();e.stopImmediatePropagation();},true);
 function cancel(){if(applying)return;session++;checkToken++;clearTimeout(checkTimer);control.detach();active=null;bar.hidden=true;dispose();navigation(true);requestRender();}
 function values(){if(!active)return null;const turn=((Math.round(-proxy.rotation.y/(Math.PI/2))%4)+4)%4,extent=turn%2?[active.size[2],active.size[1],active.size[0]]:active.size,center=parent.position.clone().add(proxy.position),at=center.toArray().map((n,a)=>Math.round(n-extent[a]/2));return{turn,at,extent};}
 function update(){if(!active)return;const v=values(),center=parent.position.clone().add(proxy.position),correction=new THREE.Vector3(...v.at.map((n,a)=>n+v.extent[a]/2-center.getComponent(a)));offset.position.copy(correction.applyQuaternion(proxy.quaternion.clone().invert()));for(const[a,id]of ['direct-dx','direct-dy','direct-dz'].entries())$(id).value=Math.round(proxy.position.getComponent(a));$('direct-edit-hint').textContent=active.mode==='rotate'?'旋转 '+v.turn*90+'° · 按 90° 吸附':'拖动箭头或平面移动 · 每格吸附';if(active.mode==='paste'){clearTimeout(checkTimer);const stamp=++checkToken;checkTimer=setTimeout(async()=>{try{const r=await call('pasteCheck',{prefab:active.prefab,at:v.at,turn:v.turn,overlap:$('direct-overlap').value,policy:policy()});if(stamp===checkToken&&active)$('direct-edit-hint').textContent=(active.floating?'移动鼠标定位 · 左键锁定 · ':'拖动微调 · ')+`放置 ${r.place} · 覆盖 ${r.replace} · 跳过 ${r.skip}`+(r.locked?' · '+r.locked+' 处保护冲突':'');}catch(e){if(stamp===checkToken&&active)$('direct-edit-hint').textContent=e.message;}},120);}bar.dataset.at=v.at.join(',');bar.dataset.phase=active.floating?'position':'adjust';if(active.floating)$('direct-edit-hint').textContent='移动鼠标定位 · 左键锁定位置 · Enter 确认 / Esc 取消';requestRender();}
 control.addEventListener('change',()=>{control.camera=getCamera();update();});control.addEventListener('dragging-changed',e=>navigation(!e.value));control.addEventListener('mouseUp',update);
 async function begin(mode,packet=null){if(loading||applying)return;if(!packet&&!hasSelection()){notice('先点击一个方块、对象，或框选需要编辑的部分');return;}cancel();const own=session;loading=true;chooseSelection();try{const r=packet?{min:packet.at,max:packet.at.map((n,a)=>n+packet.prefab.size[a]-1)}:studio.getSelection(),data=await call('selectionPreview',packet?{prefab:packet.prefab}:r);if(own!==session)return;if(!data.count){notice('选择里没有可操作的方块');return;}active={...r,mode,revision:data.revision,workspaceId:data.workspaceId,floating:mode==='paste',size:data.size,relativeMembers:data.members,...(packet?{prefab:packet.prefab}:{})};parent.position.set(...r.min.map((n,a)=>n+data.size[a]/2));proxy.position.set(0,0,0);proxy.rotation.set(0,0,0);offset.position.set(0,0,0);ghost=new THREE.Group();ghost.position.set(...data.size.map(n=>-n/2));for(const b of data.buckets){const g=new THREE.BufferGeometry();for(const[k,array,n]of [['position',b.positions,3],['normal',b.normals,3]])g.setAttribute(k,new THREE.BufferAttribute(array,n));ghost.add(new THREE.Mesh(g,new THREE.MeshLambertMaterial({color:mode==='copy'?0x76d7c2:0x82b6ff,transparent:true,opacity:.72,depthWrite:false,side:THREE.DoubleSide})));}offset.add(ghost);control.camera=getCamera();control.setMode(mode==='rotate'?'rotate':'translate');control.showX=mode!=='rotate';control.showZ=mode!=='rotate';control.showY=true;if(!active.floating)control.attach(proxy);bar.hidden=false;$('direct-edit-label').textContent=({move:'移动选择',copy:'复制选择',rotate:'旋转选择',paste:'粘贴预览'})[mode];$('direct-quarter').hidden=false;$('direct-overlap-label').hidden=mode!=='paste';for(const id of ['direct-dx','direct-dy','direct-dz'])$(id).closest('label').hidden=mode==='rotate';update();if(active.floating&&pointer)locate(pointer);}catch(e){notice(e.message,true);cancel();}finally{loading=false;}}
 function chooseSelection(){window.dispatchEvent(new Event('craftstudio-transform-start'));document.querySelector('[data-tool="inspect"]').click();}
 for(const[a,id]of ['direct-dx','direct-dy','direct-dz'].entries())$(id).oninput=()=>{if(!active)return;proxy.position.setComponent(a,Math.round(Number($(id).value)||0));update();};$('direct-overlap').onchange=update;$('direct-quarter').onclick=()=>{proxy.rotation.y-=Math.PI/2;update();};$('direct-cancel').onclick=cancel;
 async function apply(){if(!active||applying)return;const snapshot=active,v=values();if(v.at.some(n=>n<0||n>=4096)){notice('目标超出当前场景范围，请把选择移回画布');return;}if(snapshot.mode!=='paste'&&v.at.every((n,a)=>n===snapshot.min[a])&&!v.turn){notice('还没有改变位置，可以拖动箭头或输入位移');return;}applying=true;control.enabled=false;$('direct-apply').disabled=true;try{refresh(await call('studio',snapshot.mode==='paste'?{expectedRevision:snapshot.revision,workspaceId:snapshot.workspaceId,command:'paste',prefab:snapshot.prefab,at:v.at,turn:v.turn,overlap:$('direct-overlap').value,policy:policy()}:{expectedRevision:snapshot.revision,workspaceId:snapshot.workspaceId,command:'transform',min:snapshot.min,max:snapshot.max,at:v.at,members:snapshot.members,regions:snapshot.regions,move:snapshot.mode!=='copy',turn:v.turn,policy:policy()}));await render();markDirty();applying=false;cancel();const members=(snapshot.relativeMembers||snapshot.prefab?.blocks.map(b=>b.pos)||[]).map(pos=>{let[x,y,z]=pos,[w,,l]=snapshot.size;for(let t=0;t<v.turn;t++){[x,z]=[l-1-z,x];[w,l]=[l,w];}return[x,y,z].map((n,a)=>n+v.at[a]);});studio.selectRange({min:v.at,max:v.at.map((n,a)=>n+v.extent[a]-1),members},'replace');notice(snapshot.mode==='paste'?'已粘贴，可一次撤销':snapshot.mode==='copy'?'已复制，可继续移动新选择':snapshot.mode==='rotate'?'已旋转，可一次撤销':'已移动，可一次撤销');}catch(e){notice(e.message,true);}finally{applying=false;control.enabled=true;$('direct-apply').disabled=false;}}
 $('direct-apply').onclick=apply;window.addEventListener('keydown',e=>{if(!active||e.isComposing)return;if(textEditing(document.activeElement)&&e.key!=='Escape'&&!(e.key==='Enter'&&bar.contains(document.activeElement)))return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();cancel();}if(e.key==='Enter'||e.ctrlKey&&e.key.toLowerCase()==='v'&&active.mode==='paste'){e.preventDefault();e.stopImmediatePropagation();apply();}},true);
 async function copy(){if(!hasSelection()){notice('先选择需要复制的方块或对象');return;}const token=++copyToken,selection=structuredClone(studio.getSelection());clipboard=null;copying=(async()=>{try{const prefab=await call('copySelection',selection);if(token!==copyToken)return;clipboard={prefab,at:[...selection.min]};notice('已复制 '+prefab.blocks.length+' 个方块，Ctrl+V 预览粘贴');}catch(e){notice(e.message,true);}finally{if(token===copyToken)copying=null;}})();return copying;}
 async function paste(){if(copying)await copying;if(!clipboard){notice('先用 Ctrl+C 复制选择');return;}const at=pointer?pointerAnchor(pointer)||clipboard.at:[...clipboard.at];await begin('paste',{prefab:clipboard.prefab,at});}
 return{begin,cancel,copy,paste,isActive:()=>!!active,isBusy:()=>applying,ensureFresh:s=>{if(active&&!applying&&(active.revision!==s.revision||active.workspaceId!==s.workspaceId)){cancel();notice('场景已更新，旧变换预览已取消；可重新选择继续设计');}},updateCamera:()=>control.camera=getCamera()};
}
