import {closeSweepFrames} from './closed-sweep.js';
import {scopeConstruction} from './construction-scope.js';
import {prepareProfileSweep,prepareVariableSweep,profileSweepOperations} from './profile-sweep.js';
import {workplane,profileFrame,toPlane,fromPlane} from './workplane.js';
import {closedProfiles} from './sketch-profiles.js';
import {coordKey} from './site.js';
const planes={xz:[0,2,1],xy:[0,1,2],yz:[2,1,0]};
const inside=(x,y,p)=>{let result=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])result=!result;}return result;};
function edgeDistance(x,y,p){let best=Infinity;for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy||1)));best=Math.min(best,Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy));}return best;}
export function resampleProfile(points,count=64){const p=points.map(v=>[...v]);if(p.length>1&&Math.hypot(...p[0].map((n,a)=>n-p.at(-1)[a]))<1e-6)p.pop();if(p.length<3)throw Error('截面至少需要三个点');const lengths=p.map((v,i)=>Math.hypot(...v.map((n,a)=>n-p[(i+1)%p.length][a]))),total=lengths.reduce((a,b)=>a+b,0);if(!total)throw Error('截面没有面积');const out=[];for(let i=0;i<count;i++){let d=total*i/count,j=0;while(j<lengths.length-1&&d>lengths[j])d-=lengths[j++];const t=d/(lengths[j]||1);out.push(p[j].map((n,a)=>n+(p[(j+1)%p.length][a]-n)*t));}return out;}
function matchProfiles(a,b,u,v){const center=p=>[u,v].map(k=>p.reduce((n,q)=>n+q[k],0)/p.length),ca=center(a),cb=center(b);let best=null,score=Infinity;for(const reverse of [false,true])for(let shift=0;shift<a.length;shift++){const p=b.map((_,i)=>b[(reverse?b.length-1-i+shift:i+shift)%b.length]),cost=p.reduce((n,q,i)=>n+(q[u]-cb[0]-(a[i][u]-ca[0]))**2+(q[v]-cb[1]-(a[i][v]-ca[1]))**2,0);if(cost<score){score=cost;best=p;}}return best;}
export function featurePlan(site,config){return scopeConstruction(featureUnscoped(site,config),config);}
function featureUnscoped(site,config){const{operation='extrude',plane='auto',state={Name:'minecraft:stone_bricks'},hollow=false,thickness=1,cut=false}=config,[u,v,normal]=planes[plane]||planes.xz,ops=new Map(),guide=[],warnings=[];if(!Number.isFinite(+thickness)||thickness<.5||thickness>64)throw Error('壁厚应为 0.5–64 格');const put=(pos,blockState=state)=>{pos=pos.map(Math.floor);if(pos.some(n=>n<0||n>=4096))throw Error('生成结果超出画布，请移动轮廓或缩小距离');ops.set(coordKey(...pos),{type:'set',pos,state:cut?null:blockState,reason:cut?'轮廓切除':operation==='loft'?'截面放样':operation==='sweep'?'路径扫掠':'轮廓拉伸'});if(ops.size>250000)throw Error('本次体积过大，请分区生成');};
 const availableProfiles=closedProfiles(site.design.guides);const getProfile=id=>{const saved=availableProfiles.find(g=>g.id===id);if(!saved)throw Error('未找到闭合截面：请让线段端点重合，并处于同一工作平面');return saved.points;};
 if(operation==='sweep'&&config.sweepMode!==undefined&&!['profile','rectangle'].includes(config.sweepMode))throw Error('请选择自绘截面或快速矩形');const sections=operation==='sweep'&&config.sweepMode!=='profile'?[]:config.profiles?.length?config.profiles.map(p=>p.points||p):config.profileIds?.map(getProfile)||[];
 if(operation==='sweep'){const source=config.path||site.design.guides?.find(g=>g.id===config.pathId)?.points;if(!source?.length)throw Error('请先绘制并选择一条路径');if(config.sweepMode==='profile'){if(!sections.length)throw Error('请选择闭合截面；先在路径上绘制截面');const references=sections.map((p,i)=>availableProfiles.find(g=>g.id===config.profileIds?.[i])?.recipe.workplane||config.profiles?.[i]?.workplane||config.workplane),rawPlan=prepareVariableSweep(source,sections,references,config.profileStations?config:{...config,profileStations:sections.map((p,i)=>{const source=availableProfiles.find(g=>g.id===config.profileIds?.[i])?.recipe.workplaneSource;return source?.kind==='curve-station'&&source.guideId===config.pathId?source.station:null;})}),plan=closeSweepFrames(rawPlan,source,config);const fit=profileSweepOperations(plan,config,put);return{operations:[...ops.values()],guide:[...source],guideGroups:[source,...plan.segments.filter((s,i)=>i===plan.segments.length-1||i%Math.max(1,Math.ceil(plan.segments.length/7))===0).map(s=>[...s.rings[0],s.rings[0][0]]),[...plan.segments.at(-1).rings[1],plan.segments.at(-1).rings[1][0]]],warnings:plan.warnings,usedRoles:fit.usedRoles,closure:plan.closure||null,overlap:plan.overlap||null,blocked:plan.blocked||null,sweep:{segments:plan.segments.length,closed:plan.closed,profilePoints:plan.poly.length}};}const width=Number(config.width??3),height=Number(config.height??3);if(!Number.isFinite(width)||!Number.isFinite(height)||width<1||height<1||width>64||height>64||source.length*width*height>1000000)throw Error('路径或截面过大，请缩小宽高或分段生成');warnings.push('沿路径生成使用竖直矩形截面；弯道会合并重叠方块');for(let i=0;i<source.length;i++){const p=source[i],next=source[Math.min(i+1,source.length-1)],before=source[Math.max(0,i-1)],dir=next.map((n,a)=>n-before[a]),horizontal=Math.hypot(dir[0],dir[2]),right=horizontal>1e-6?[dir[2]/horizontal,0,-dir[0]/horizontal]:[1,0,0];guide.push(p);for(let x=-width/2;x<=width/2;x+=.5)for(let y=0;y<height;y+=.5){if(hollow&&Math.abs(x)<width/2-thickness&&y>=thickness&&y<height-thickness)continue;put(p.map((n,a)=>n+right[a]*x+(a===1?y:0)));}}return{operations:[...ops.values()],guide,warnings,usedRoles:{}};}
 if(!sections.length)throw Error('未找到闭合截面：请保存轮廓，确保线段端点重合、没有分叉，并处于同一平面');const reference=availableProfiles.find(g=>g.id===config.profileIds?.[0])?.recipe.workplane||config.workplane,frame=profileFrame(sections[0],plane,reference);if(plane==='auto'){if(frame.plane!=='auto')return featureUnscoped(site,{...config,plane:frame.plane});return orientedPlan(sections,config,frame,put,ops);}let profiles=sections.map(p=>resampleProfile(p));const first=profiles[0];if(operation==='extrude'){const depth=Number(config.depth??8);if(!Number.isFinite(depth)||Math.abs(depth)<.5)throw Error('请输入有效拉伸距离');const end=first.map(p=>p.map((n,a)=>n+(a===normal?depth:0)));profiles=config.symmetric?[first.map(p=>p.map((n,a)=>n-(a===normal?depth/2:0))),first.map(p=>p.map((n,a)=>n+(a===normal?depth/2:0)))]:[first,end];}
 else if(operation==='loft'){if(profiles.length<2)throw Error('放样至少需要两个截面');profiles.sort((a,b)=>a[0][normal]-b[0][normal]);for(let i=1;i<profiles.length;i++)profiles[i]=matchProfiles(profiles[i-1],profiles[i],u,v);}
 else throw Error('未知建模操作');
 for(const p of profiles){const level=p[0][normal];if(p.some(q=>Math.abs(q[normal]-level)>.05))throw Error('截面不在所选工作平面上，请选择正确平面');guide.push(...p,p[0]);}
 for(let section=0;section<profiles.length-1;section++){const a=profiles[section],b=profiles[section+1],lo=Math.min(a[0][normal],b[0][normal]),hi=Math.max(a[0][normal],b[0][normal]);if(hi-lo<.01)throw Error('放样截面高度相同，请移动其中一个截面');for(let layer=Math.floor(lo);layer<Math.ceil(hi);layer++){let t=Math.max(0,Math.min(1,(layer+.5-a[0][normal])/(b[0][normal]-a[0][normal])));if(config.smooth)t=t*t*(3-2*t);const poly=a.map((p,i)=>[p[u]+(b[i][u]-p[u])*t,p[v]+(b[i][v]-p[v])*t]),min=[0,1].map(k=>Math.floor(Math.min(...poly.map(p=>p[k])))),max=[0,1].map(k=>Math.ceil(Math.max(...poly.map(p=>p[k]))));if((max[0]-min[0])*(max[1]-min[1])>65536)throw Error('截面太大，请分区生成');for(let x=min[0];x<max[0];x++)for(let y=min[1];y<max[1];y++)if(inside(x+.5,y+.5,poly)){const cap=config.caps!==false&&(layer-lo<thickness||hi-layer-1<thickness);if(hollow&&!cap&&edgeDistance(x+.5,y+.5,poly)>thickness)continue;const pos=[0,0,0];pos[u]=x;pos[v]=y;pos[normal]=layer;put(pos);}}}
 return{operations:[...ops.values()],guide,warnings,usedRoles:{}};
}

function orientedPlan(sections,config,frame,put,ops){
 const operation=config.operation||'extrude',depth=Number(config.depth??8),thickness=Number(config.thickness??1),guide=[];
 let profiles=sections.map(p=>{const local=p.map(q=>toPlane(q,frame));if(local.some(q=>Math.abs(q[2]-local[0][2])>1e-4))throw Error('放样截面需要位于相互平行的平面');return resampleProfile(local);});
 if(operation==='extrude'){if(!Number.isFinite(depth)||Math.abs(depth)<.5)throw Error('请输入有效拉伸距离');const first=profiles[0],start=config.symmetric?-depth/2:0;profiles=[first.map(p=>[p[0],p[1],p[2]+start]),first.map(p=>[p[0],p[1],p[2]+start+depth])];}
 else if(operation==='loft'){if(profiles.length<2)throw Error('放样至少需要两个截面');profiles.sort((a,b)=>a[0][2]-b[0][2]);for(let i=1;i<profiles.length;i++)profiles[i]=matchProfiles(profiles[i-1],profiles[i],0,1);}
 else throw Error('未知建模操作');
 let visited=0;
 for(const p of profiles)guide.push(...[...p,p[0]].map(q=>fromPlane(q,frame)));
 for(let section=0;section<profiles.length-1;section++){
  const a=profiles[section],b=profiles[section+1],lo=Math.min(a[0][2],b[0][2]),hi=Math.max(a[0][2],b[0][2]);if(hi-lo<.01)throw Error('放样截面高度相同，请移动其中一个截面');
  const world=[...a,...b].map(p=>fromPlane(p,frame)),min=[0,1,2].map(i=>Math.floor(Math.min(...world.map(p=>p[i])))),max=[0,1,2].map(i=>Math.ceil(Math.max(...world.map(p=>p[i]))));
  visited+=max.reduce((v,n,i)=>v*(n-min[i]),1);if(visited>2000000)throw Error('倾斜体积过大，请分区生成');
  for(let x=min[0];x<max[0];x++)for(let y=min[1];y<max[1];y++)for(let z=min[2];z<max[2];z++){
   const p=toPlane([x+.5,y+.5,z+.5],frame);if(p[2]<lo-1e-8||p[2]>=hi-1e-8)continue;
   let t=(p[2]-a[0][2])/(b[0][2]-a[0][2]);if(config.smooth)t=t*t*(3-2*t);const poly=a.map((q,i)=>[q[0]+(b[i][0]-q[0])*t,q[1]+(b[i][1]-q[1])*t]);
   if(!inside(p[0],p[1],poly))continue;const cap=config.caps!==false&&(p[2]-lo<thickness||hi-p[2]<thickness);if(config.hollow&&!cap&&edgeDistance(p[0],p[1],poly)>thickness)continue;put([x,y,z]);
  }
 }
 return{operations:[...ops.values()],guide,warnings:['倾斜体积按世界方块网格落格；边界呈阶梯状'],usedRoles:{}};
}
