import {segmentMetrics} from './measurement.js';import {textEditing} from './keyboard-context.js';
export function measurementUI({THREE,$,scene,renderer,cast,getSummary,getCamera,beforeOpen,call,refresh,render,markDirty,notice,requestRender}){
 const panel=document.createElement('section');panel.id='measurement-panel';panel.hidden=true;panel.className='workspace-task-panel';panel.innerHTML='<div class="construction-header"><strong>测量间距与高差</strong><button id="measurement-close">结束</button></div><label>名称<input id="measurement-name" value="场地测量"></label><label>吸附<select id="measurement-snap"><option value="0.5">半格 · 半砖高度</option><option value="1">整格</option><option value="0">表面位置 · 不吸附</option></select></label><p id="measurement-stage">点取起点，再点取终点</p><div id="measurement-points"></div><pre id="measurement-report" aria-live="polite"></pre><p class="small">单位为格；读数表示点间距离，不是材料数量。标注保存当前位置快照。</p><div class="row"><button id="measurement-restart">重新取点</button><button id="measurement-save" class="primary" disabled>保存标注</button></div>';$('scene').append(panel);
 const saved=document.createElement('section');saved.className='inspector-section';saved.id='measurement-saved';saved.hidden=true;saved.innerHTML='<h3>测量标注</h3><label class="check"><input id="measurement-visible" type="checkbox" checked>显示已保存标注</label><div id="measurement-list"></div>';$('cad-selected-properties').after(saved);
 const temporary=new THREE.Group(),persistent=new THREE.Group();scene.add(temporary,persistent);let active=false,points=[],editingId=null,signature='',workspaceId=null,navigationHeld=false,saving=false,down=null;
 const number=n=>Number(n.toFixed(3)).toLocaleString();
 function dispose(group){for(const node of [...group.children]){group.remove(node);node.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});}}
 function draw(group,positions,color){dispose(group);if(!positions.length)return;for(const pos of positions){const node=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),new THREE.MeshBasicMaterial({color,depthTest:false}));node.position.set(...pos);group.add(node);}if(positions.length!==2)return;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(positions.map(p=>new THREE.Vector3(...p))),new THREE.LineBasicMaterial({color,depthTest:false}));group.add(line);const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const ctx=canvas.getContext('2d'),text=number(segmentMetrics(positions).distance)+' 格';ctx.font='26px sans-serif';canvas.width=Math.max(96,Math.ceil(ctx.measureText(text).width)+24);ctx.fillStyle='rgba(28,39,53,.9)';ctx.fillRect(0,0,canvas.width,64);ctx.fillStyle='#f1f6ff';ctx.font='26px sans-serif';ctx.textAlign='center';ctx.fillText(text,canvas.width/2,42);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false,depthWrite:false}));sprite.position.set(...positions[0].map((n,a)=>(n+positions[1][a])/2));sprite.onBeforeRender=(r,sc,camera)=>{const height=Math.max(1,r.domElement.clientHeight),perPixel=camera.isOrthographicCamera?(camera.top-camera.bottom)/camera.zoom/height:2*camera.position.distanceTo(sprite.position)*Math.tan(camera.fov*Math.PI/360)/height;sprite.scale.set(perPixel*canvas.width/2,perPixel*32,1);};group.add(sprite);}
 function report(preview=points){$('measurement-save').disabled=points.length!==2||saving;if(preview.length!==2){$('measurement-report').textContent='点取两处实际位置后显示距离与高差';return;}const m=segmentMetrics(preview);$('measurement-report').textContent=`直线间距  ${number(m.distance)} 格\n水平间距  ${number(m.horizontal)} 格\n高差 ΔY   ${number(m.rise)} 格\nΔX / ΔZ   ${number(m.delta[0])} / ${number(m.delta[2])} 格\n轴向总距  ${number(m.manhattan)} 格\n坡度      ${m.slopePercent===null?(m.distance?'垂直':'两点重合'):number(m.slopePercent)+'%'} · ${number(m.pitchDegrees)}°`;}
 function pointRows(){const host=$('measurement-points');host.replaceChildren(...points.map((pos,i)=>{const row=document.createElement('div');row.className='cad-vector';const name=document.createElement('strong');name.textContent=i?'终点':'起点';row.append(name);for(let a=0;a<3;a++){const label=document.createElement('label');label.textContent='XYZ'[a];const input=document.createElement('input');input.type='number';input.step='.5';input.value=pos[a];input.setAttribute('aria-label',(i?'终点':'起点')+' '+'XYZ'[a]);input.oninput=()=>{const value=Number(input.value);if(!Number.isFinite(value))return;points[i][a]=value;draw(temporary,points,0xffcf72);report();requestRender();};label.append(input);row.append(label);}return row;}));}
 function close(){if(saving)return;active=false;down=null;panel.hidden=true;points=[];editingId=null;dispose(temporary);requestRender();}
 function start(item=null){if(saving)return;try{beforeOpen();}catch(e){notice(e.message,true);return;}active=true;editingId=item?.id||null;points=item?structuredClone(item.points):[];$('measurement-name').value=item?.name||'场地测量';panel.hidden=false;$('measurement-stage').textContent=item?'修改坐标，或重新取点':'点取起点，再点取终点';pointRows();report();draw(temporary,points,0xffcf72);renderer.domElement.focus({preventScroll:true});requestRender();}
 function pick(e){const hit=cast(e);if(!hit)return null;const step=Number($('measurement-snap').value),pos=hit.point.toArray();return pos.map(n=>step?Math.round(n/step)*step:n);}
 renderer.domElement.addEventListener('pointerdown',e=>{if(!active||e.button!==0||e.altKey||navigationHeld)return;down={x:e.clientX,y:e.clientY,pointerId:e.pointerId};e.preventDefault();e.stopImmediatePropagation();},true);
 renderer.domElement.addEventListener('pointerup',e=>{if(!active||e.button!==0||e.altKey||navigationHeld)return;e.preventDefault();e.stopImmediatePropagation();if(!down||down.pointerId!==e.pointerId||Math.hypot(e.clientX-down.x,e.clientY-down.y)>5){down=null;return;}down=null;const pos=pick(e);if(!pos)return;if(points.length===2)points=[];points.push(pos);pointRows();report();draw(temporary,points,0xffcf72);$('measurement-stage').textContent=points.length===2?'可修改坐标或保存标注':'点取终点 · 鼠标移动实时显示间距';requestRender();},true);
 renderer.domElement.addEventListener('pointermove',e=>{if(!active||points.length!==1||e.buttons||e.altKey||navigationHeld)return;const pos=pick(e);if(pos){draw(temporary,[points[0],pos],0xffcf72);report([points[0],pos]);requestRender();}});
 renderer.domElement.addEventListener('pointercancel',()=>down=null);window.addEventListener('blur',()=>{down=null;navigationHeld=false;});
 window.addEventListener('keydown',e=>{if(e.target.closest?.('[data-shortcut-scope=commands]')||e.isComposing)return;if(e.code==='Space'&&!textEditing(document.activeElement))navigationHeld=true;if(active&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();}},true);window.addEventListener('keyup',e=>{if(e.code==='Space')navigationHeld=false;});
 async function change(method,params){const s=getSummary(),r=await call('api',{method,params:{expectedRevision:s.revision,workspaceId:s.workspaceId,...params}});if(!r.ok)throw Error(r.error.message);refresh(await call('summary'));await render();markDirty();return r;}
 $('measurement-close').onclick=close;$('measurement-restart').onclick=()=>{points=[];editingId=null;pointRows();report();dispose(temporary);$('measurement-stage').textContent='点取起点，再点取终点';requestRender();};$('measurement-visible').onchange=()=>{persistent.visible=$('measurement-visible').checked;requestRender();};
 $('measurement-save').onclick=async()=>{if(points.length!==2||saving)return;saving=true;report();try{await change('measurements.put',{measurement:{...(editingId?{id:editingId}:{}),name:$('measurement-name').value,points}});saving=false;close();notice('测量标注已保存，可一次撤销');}catch(e){notice(e.message,true);}finally{saving=false;report();}};
 return{open:start,close,isActive:()=>active,isBusy:()=>saving,update:s=>{if(workspaceId&&workspaceId!==s.workspaceId)close();workspaceId=s.workspaceId;const list=s.design?.measurements||[],next=JSON.stringify(list);saved.hidden=!list.length;if(next===signature)return;signature=next;dispose(persistent);for(const item of list){const group=new THREE.Group();draw(group,item.points,0x8fbae8);persistent.add(group);}$('measurement-list').replaceChildren(...list.map(item=>{const row=document.createElement('div');row.className='row';const edit=document.createElement('button'),remove=document.createElement('button');edit.textContent=item.name+' · '+number(segmentMetrics(item.points).distance)+' 格';edit.onclick=()=>start(item);remove.textContent='删除';remove.onclick=()=>change('measurements.remove',{id:item.id}).catch(e=>notice(e.message,true));row.append(edit,remove);return row;}));requestRender();}};
}
