import {VoxelOverlayMap} from './voxel-overlay-map.js';
import { emptyProject, stateKey } from './codec.js';
export const coordKey=(x,y,z)=>x+4096*(z+4096*y);
export const coords=k=>[k%4096,Math.floor(k/16777216),Math.floor(k/4096)%4096];
export const chunkKey=pos=>pos.map(v=>Math.floor(v/16)).join(',');
export function terrainType(name){if(/:(water|lava)$/.test(name))return'water';if(/:(stone|andesite|diorite|granite|dirt|coarse_dirt|rooted_dirt|grass_block|gravel|sand|red_sand|clay|deepslate|tuff|calcite|mud|moss_block|snow_block|bedrock|netherrack|end_stone)$/.test(name)||/_ore$/.test(name))return'ground';if(/leaves|sapling|short_grass|tall_grass|pink_petals|flower|fern|vine/.test(name))return'plant';return'building';}
export function validateProject(p){if(p.schema!==1||!Array.isArray(p.palette)||!Array.isArray(p.blocks)||p.size?.length!==3||p.size.some(n=>!Number.isInteger(n)||n<1||n>4096))throw Error('工程结构或尺寸无效');const seen=new Set();for(const s of p.palette)if(typeof s.Name!=='string'||!s.Name.includes(':'))throw Error('需要 namespace:方块ID');for(const b of p.blocks){if(b.pos.length!==3||b.pos.some((v,a)=>!Number.isInteger(v)||v<0||v>=p.size[a])||!p.palette[b.state])throw Error('方块坐标或调色板无效');const k=coordKey(...b.pos);if(seen.has(k))throw Error('工程包含重复位置');seen.add(k);}return p;}
export class Site{
 constructor(project=emptyProject()){
  this.base=validateProject(project);this.palette=project.palette.map(s=>structuredClone(s));this.states=new Map(this.palette.map((s,i)=>[stateKey(s),i]));this.cells=new VoxelOverlayMap();this.overlay=new VoxelOverlayMap();this.size=[...project.size];this.origin=[...project.origin];this.originConfirmed=!!project.metadata?.originConfirmed;this.protected=[];this.title=project.name;this.sourceHash=project.metadata?.sourceHash||'';this.undo=[];this.redo=[];this.columns=null;
  this.baseChunks=new Map();this.overlayChunks=new Map();this.ownedOverlayChunks=new Set();this.summaryCounts={add:0,remove:0,replace:0,earth:0,water:0,materials:{}};this.changedPositions=[];this.blockEntityCount=0;this.design=structuredClone(project.metadata?.design||{objects:[],prefabs:[],animations:{},cameras:[],lighting:"day"});this.stroke=false;this.strokeRecorded=false;this.lastSkipped=0;
  for(const b of project.blocks){this.cells.set(coordKey(...b.pos),b);if(b.nbt)this.blockEntityCount++;}
  for(const [id,chunk]of this.cells.chunks)this.baseChunks.set([id&255,id>>>16,(id>>>8)&255].join(','),chunk);
 }
 beginStroke(){this.stroke=true;this.strokeRecorded=false;}
 fork(){const site=Object.create(Site.prototype);Object.assign(site,this);site.palette=[...this.palette];site.states=new Map(this.states);site.overlay=new VoxelOverlayMap(this.overlay);site.overlayChunks=new Map(this.overlayChunks);this.ownedOverlayChunks.clear();site.ownedOverlayChunks=new Set();site.summaryCounts={...this.summaryCounts,materials:{...this.summaryCounts.materials}};site.size=[...this.size];site.origin=[...this.origin];site.protected=structuredClone(this.protected);site.design=structuredClone(this.design);site.changedPositions=[];site.undo=[];site.redo=[];site.stroke=false;site.strokeRecorded=false;return site;}
 endStroke(){this.stroke=false;this.strokeRecorded=false;}
 track(previous,next,keys=null){this.changedPositions=[];for(const k of keys||new Set([...previous.keys(),...next.keys()])){const old=previous.get(k),b=next.get(k);if(old?.state===b?.state&&JSON.stringify(old?.nbt||null)===JSON.stringify(b?.nbt||null))continue;const pos=b?.pos||old?.pos;if(!pos)continue;this.countOverlay(k,old,-1);this.countOverlay(k,b,1);this.changedPositions.push(pos);const id=chunkKey(pos);if(!this.ownedOverlayChunks.has(id)){this.overlayChunks.set(id,new Map(this.overlayChunks.get(id)||[]));this.ownedOverlayChunks.add(id);}if(b){this.overlayChunks.get(id).set(k,b);}else{this.overlayChunks.get(id)?.delete(k);if(!this.overlayChunks.get(id)?.size){this.overlayChunks.delete(id);this.ownedOverlayChunks.delete(id);}}}}
 state(s){const key=stateKey(s);if(!this.states.has(key)){this.states.set(key,this.palette.length);this.palette.push(structuredClone(s));}return this.states.get(key);}
 at(pos,original=false){const k=coordKey(...pos);if(!original&&this.overlay.has(k)){const b=this.overlay.get(k);return b.state<0?null:b;}return this.cells.get(k)||null;}
 allowed(pos,policy){const b=this.at(pos,true);if(this.protected.some(r=>pos.every((v,a)=>v>=r.min[a]&&v<=r.max[a])))throw Error('这个位置属于你锁定的保留区：'+pos.join(', '));if(!b)return;const type=terrainType(this.palette[b.state].Name);if((type==='ground'||type==='water')&&!policy.allowTerrain)throw Error('原地形/河水保持锁定；请调整建筑标高，或明确开启土方改动。位置 '+pos.join(', '));if((type==='building'||type==='plant')&&!policy.allowExisting)throw Error('原有建筑/植被保持锁定；可另选空地，或明确开启既有建筑改动。位置 '+pos.join(', '));}
 operations(operations,policy={allowTerrain:false,allowExisting:false}){
  const paletteBefore=this.palette,statesBefore=this.states;this.palette=[...this.palette];this.states=new Map(this.states);const next=new VoxelOverlayMap(this.overlay),changes=new Map();this.lastSkipped=0;
  const set=(pos,state,reason='手工编辑',nbt=undefined)=>{if(pos.some(n=>!Number.isInteger(n)||n<0||n>=4096))throw Error('工程局部坐标需为 0–4095 的整数');if(state?.Name==='minecraft:structure_void')return;const key=coordKey(...pos),candidate=next.has(key)?next.get(key):this.cells.get(key),old=candidate?.state>=0?candidate:null;const index=state?.Name&&state.Name!=='minecraft:air'?this.state(state):-1;const before=this.at(pos,true);if((old?.state??-1)===index&&(nbt===undefined||JSON.stringify(old?.nbt||null)===JSON.stringify(nbt)))return;try{if(this.design.objects.some(o=>o.locked&&pos.every((n,a)=>n>=o.min[a]&&n<=o.max[a])))throw Error('这个对象已锁定');this.allowed(pos,policy);}catch(error){if(!policy.skipLocked)throw error;this.lastSkipped++;return;}const effectiveNBT=nbt===undefined&&index===before?.state?before.nbt:nbt;const entry={pos:[...pos],state:index,reason,...(effectiveNBT?{nbt:structuredClone(effectiveNBT)}:{})};if(index===(before?.state??-1)&&JSON.stringify(effectiveNBT||null)===JSON.stringify(before?.nbt||null))next.delete(key);else next.set(key,entry);changes.set(key,entry);};
  try{
  for(const op of operations){if(op.type==='replace'){if(!op.state||!op.from)throw Error('替换操作缺少材料');const all=new Map(this.cells);for(const[k,b]of next)if(b.state<0)all.delete(k);else all.set(k,b);for(const b of all.values())if(this.palette[b.state].Name===op.from)set(b.pos,op.state,op.reason,op.nbt);continue;}if(!['set','fill','erase'].includes(op.type))throw Error('不支持操作 '+op.type);const lo=op.type==='set'?op.pos:op.min,hi=op.type==='set'?op.pos:op.max;if(lo?.length!==3||hi?.length!==3||lo.some((v,a)=>!Number.isInteger(v)||!Number.isInteger(hi[a])||v>hi[a]))throw Error('无效操作选区');const count=hi.reduce((n,v,a)=>n*(v-lo[a]+1),1);if(count>1000000)throw Error('请把这次操作拆成几个较小选区');for(let y=lo[1];y<=hi[1];y++)for(let z=lo[2];z<=hi[2];z++)for(let x=lo[0];x<=hi[0];x++)set([x,y,z],op.type==='erase'?null:op.state,op.reason,op.nbt);}
  }catch(error){this.palette=paletteBefore;this.states=statesBefore;throw error;}this.track(this.overlay,next,changes.keys());if(this.changedPositions.length){if(!this.stroke||!this.strokeRecorded){this.undo.push({overlay:this.overlay,size:[...this.size],design:structuredClone(this.design)});if(this.undo.length>30)this.undo.shift();this.strokeRecorded=true;}this.redo=[];}this.overlay=next;for(const b of changes.values())this.size=this.size.map((v,a)=>Math.max(v,b.pos[a]+1));return this.summary();
 }
 restore(which){this.endStroke();const source=which==='undo'?this.undo:this.redo,target=which==='undo'?this.redo:this.undo;if(!source.length){this.changedPositions=[];return;}target.push({overlay:this.overlay,size:[...this.size],design:structuredClone(this.design)});const item=source.pop();this.track(this.overlay,item.overlay);this.overlay=item.overlay;this.size=item.size;if(item.design)this.design=structuredClone(item.design);}
 diff(){const out=[];for(const[k,b]of this.overlay){const old=this.cells.get(k),before=old?this.palette[old.state]:null,after=b.state<0?null:this.palette[b.state];out.push({pos:b.pos,before,after,action:!old?'add':b.state<0?'remove':'replace',category:before?terrainType(before.Name):'air',reason:b.reason||'编辑'});}return out.sort((a,b)=>a.pos[1]-b.pos[1]||a.pos[2]-b.pos[2]||a.pos[0]-b.pos[0]);}
 countOverlay(key,block,sign){if(!block)return;const c=this.summaryCounts,before=this.cells.get(key);c[!before?'add':block.state<0?'remove':'replace']+=sign;if(before){const type=terrainType(this.palette[before.state].Name);if(type==='ground')c.earth+=sign;if(type==='water')c.water+=sign;}if(block.state>=0){const name=this.palette[block.state].Name;c.materials[name]=(c.materials[name]||0)+sign;if(!c.materials[name])delete c.materials[name];}}
 summary(){const{add,remove,replace,earth,water}=this.summaryCounts,materials={...this.summaryCounts.materials};return{sourceBlocks:this.cells.size,changes:this.overlay.size,add,remove,replace,earth,water,size:this.size,sourceSize:this.base.size,origin:this.origin,originConfirmed:this.originConfirmed,palette:this.palette,entities:(this.base.entities||[]).length,blockEntities:this.blockEntityCount,materials,design:this.design,protected:this.protected,undo:this.undo.length,redo:this.redo.length,skipped:this.lastSkipped,name:this.title,warnings:this.base.warnings||[]};}
 project(){const all=new Map(this.cells);for(const[k,b]of this.overlay)if(b.state<0)all.delete(k);else all.set(k,{pos:b.pos,state:b.state,...(b.nbt?{nbt:b.nbt}:{})});return{...(this.baseline?.header||this.base),name:this.title,size:this.size,palette:this.palette,blocks:[...all.values()],origin:this.origin,metadata:{...this.base.metadata,originConfirmed:this.originConfirmed,protected:this.protected,design:this.design}};}
 packHeader(){return{title:this.title,origin:this.origin,originConfirmed:this.originConfirmed,protected:this.protected,palette:this.palette,sourceHash:this.sourceHash,design:structuredClone(this.design)};}
 pack(){return{base:this.base,...this.packHeader(),overlay:[...this.overlay.values()].map(b=>({...b,state:b.state<0?null:this.palette[b.state]}))};}
 static unpack(p){const site=new Site(p.base);site.title=p.title||p.base.name;site.origin=p.origin||p.base.origin;site.originConfirmed=!!p.originConfirmed;site.protected=p.protected||[];site.sourceHash=p.sourceHash||'';site.design=structuredClone(p.design||site.design);for(const b of p.overlay||[]){const entry={...b,state:b.state?site.state(b.state):-1};site.overlay.set(coordKey(...entry.pos),entry);site.size=site.size.map((v,a)=>Math.max(v,entry.pos[a]+1));}site.track(new Map(),site.overlay);return site;}
 inspect(pos){const before=this.at(pos,true),after=this.at(pos);return{pos,world:this.originConfirmed?pos.map((v,a)=>v+this.origin[a]):null,before:before?this.palette[before.state]:null,after:after?this.palette[after.state]:null,nbt:before?.nbt||null,reason:this.overlay.get(coordKey(...pos))?.reason||'原有保留',column:this.column(pos[0],pos[2])};}
 column(x,z){if(this.baseline)return this.baseline.column(x,z,this.palette);if(!this.columns){this.columns=new Map();for(const b of this.base.blocks){const type=terrainType(this.palette[b.state].Name),key=b.pos[0]+4096*b.pos[2];const c=this.columns.get(key)||{ground:null,water:null,top:null};c.top=Math.max(c.top??-1,b.pos[1]);if(type==='ground')c.ground=Math.max(c.ground??-1,b.pos[1]);if(type==='water')c.water=Math.max(c.water??-1,b.pos[1]);this.columns.set(key,c);}}return this.columns.get(x+4096*z)||{ground:null,water:null,top:null};}
 heightmap(focus=null,maxSamples=1600){const[w,,l]=this.base.size,lo=focus?[Math.max(0,focus[0]-16),Math.max(0,focus[2]-16)]:[0,0],hi=focus?[Math.min(w-1,focus[0]+16),Math.min(l-1,focus[2]+16)]:[w-1,l-1],stride=focus?1:Math.max(1,Math.ceil(Math.sqrt(w*l/maxSamples))),rows=[];for(let z=lo[1];z<=hi[1];z+=stride)for(let x=lo[0];x<=hi[0];x+=stride){const c=this.column(x,z);rows.push([x,z,c.ground,c.water,c.top]);}return{columns:['local_x','local_z','original_ground_y','original_water_y','original_occupied_top_y'],min:lo,max:hi,stride,rows,classification:'地面按方块种类识别；最高占用高度包含原建筑和植物，空数据保持 null'};}
 platform(min,max,y,state,spacing=4){if(min.length!==2||max.length!==2||[...min,...max,y,spacing].some(n=>!Number.isInteger(n))||y<1||spacing<1||min.some((v,a)=>v<0||v>max[a]))throw Error('平台坐标、标高和柱距必须为有效整数');if((max[0]-min[0]+1)*(max[1]-min[1]+1)>40000)throw Error('平台范围过大，请分区设计');const operations=[{type:'fill',min:[min[0],y,min[1]],max:[max[0],y,max[1]],state,reason:'沿真实场地布置平台'}];let deepest=0;for(let x=min[0];x<=max[0];x++)for(let z=min[1];z<=max[1];z++){const c=this.column(x,z);if(c.ground===null)throw Error('选区内缺少地面数据，请导入更完整的场地；位置 '+x+', '+z);if(c.ground>=y)throw Error('实际山坡高于平台标高，建议抬高、缩短或错位；位置 '+x+', '+z);}for(let x=min[0];x<=max[0];x+=spacing)for(let z=min[1];z<=max[1];z+=spacing){const c=this.column(x,z);deepest=Math.max(deepest,y-c.ground-1);if(c.ground+1<y)operations.push({type:'fill',min:[x,c.ground+1,z],max:[x,y-1,z],state,reason:'立柱下探至原有真实地面'});}return{operations,deepest};}
}
