import {slopeHeight} from './terrain-slope.js';
export function slopePreview(THREE,scene,requestRender){
 const root=new THREE.Group();root.visible=false;scene.add(root);const lineMaterial=new THREE.LineBasicMaterial({color:0x9cd4ff,depthTest:false,transparent:true,opacity:.85}),surfaceMaterial=new THREE.MeshBasicMaterial({color:0x70bcef,transparent:true,opacity:.16,depthWrite:false,side:THREE.DoubleSide});const markerMaterial=new THREE.MeshBasicMaterial({color:0x9cd4ff,depthTest:false});let frames=0;
 function clear(){for(const node of [...root.children]){root.remove(node);node.geometry.dispose();}root.visible=false;requestRender();}
 function draw(points,bounds,{grid=true,visible=true}={}){const start=performance.now();clear();if(!points?.length)return{frames,ms:0};root.visible=visible;const samples=points.map(p=>new THREE.Vector3(p[0]+.5,p[1]+1,p[2]+.5));root.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(samples),lineMaterial));for(const p of samples){const marker=new THREE.Mesh(new THREE.SphereGeometry(.16,8,6),markerMaterial);marker.position.copy(p);root.add(marker);}if(points.length===2&&grid){
  const n=12,positions=[],lines=[];const at=(i,j)=>{const x=bounds.min[0]+(bounds.max[0]+1-bounds.min[0])*i/n,z=bounds.min[2]+(bounds.max[2]+1-bounds.min[2])*j/n;return[x,slopeHeight(points,x-.5,z-.5)+1,z];};for(let i=0;i<n;i++)for(let j=0;j<n;j++){const a=at(i,j),b=at(i+1,j),c=at(i+1,j+1),d=at(i,j+1);positions.push(...a,...b,...c,...a,...c,...d);}for(let i=0;i<=n;i++)for(let j=0;j<n;j++){lines.push(...at(i,j),...at(i,j+1),...at(j,i),...at(j+1,i));}const surface=new THREE.BufferGeometry();surface.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));root.add(new THREE.Mesh(surface,surfaceMaterial));const gridGeometry=new THREE.BufferGeometry();gridGeometry.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));root.add(new THREE.LineSegments(gridGeometry,lineMaterial));
 }frames++;requestRender();return{frames,ms:performance.now()-start};}
 return{draw,clear,setVisible:v=>{root.visible=v;requestRender();},dispose(){clear();scene.remove(root);lineMaterial.dispose();surfaceMaterial.dispose();markerMaterial.dispose();}};
}
