export function workspaceUI({$,construction,designer,direct,measurement,dock,chooseTool}){
 document.body.classList.add('studio-workspace');const left=$('cad-browser'),right=$('cad-inspector'),viewport=$('viewport');
 const tree=document.createElement('section');tree.id='workspace-tree';tree.innerHTML='<div class="workspace-caption">场景集合 <span>对象与构件</span></div>';tree.append($('dock-objects'));
 const defaults=document.createElement('div');defaults.id='workspace-properties';for(const child of [...right.children])defaults.append(child);
 const tasks=document.createElement('div');tasks.id='workspace-task';tasks.hidden=true;right.replaceChildren(tree,defaults,tasks);
 const shelf=document.createElement('section');shelf.id='workspace-shelf';shelf.hidden=true;shelf.innerHTML='<div class="workspace-shelf-header"><strong>素材与构件</strong><div id="workspace-shelf-tabs"></div><button id="workspace-shelf-close" title="收起素材架">收起 ↓</button></div><div class="workspace-shelf-body"><div id="workspace-shelf-content"></div><div id="workspace-shelf-preview"></div></div>';
 const bottom=viewport.querySelector('.scene-bottom');bottom.before(shelf);$('workspace-shelf-content').append($('dock-assets'),$('dock-components'));$('workspace-shelf-preview').append($('asset-detail'),$('dock-assets').querySelector('.asset-data'));
 const oldTabs=left.querySelector('.dock-tabs');$('workspace-shelf-tabs').append(...oldTabs.children);$('workspace-shelf-tabs').querySelector('[data-dock="objects"]').textContent='收起';
 left.replaceChildren();left.className='workspace-tools';const toolButtons=[...document.querySelectorAll('#cad-tools [data-tool]')];for(const id of ['inspect','place','paint','erase','sample']){const b=toolButtons.find(b=>b.dataset.tool===id);if(b)left.append(b);}for(const id of ['cad-rotate-direct','cad-move-direct'])left.insertBefore($(id),left.children[1]);
 const draw=document.createElement('button');draw.id='workspace-draw';draw.textContent='绘制';draw.title='绘制辅助轮廓';draw.onclick=()=>{$('cad-figure').click();};left.append(draw);const measure=document.createElement('button');measure.id='workspace-measure';measure.textContent='测量';measure.title='点取位置，测量间距、高差与坡度';measure.onclick=()=>measurement.open();left.append(measure);
 const bar=$('cad-ribbon');const allCommands=document.createElement('div');allCommands.id='workspace-commands';const groups={edit:[],draw:[],model:[],site:[]};const commandIds={edit:['cad-copy-direct','cad-paste-direct','cad-modify-open','cad-components-open'],draw:['cad-figure'],model:['cad-feature','cad-create-open','cad-designer'],site:['cad-terrain']};
 for(const[k,ids]of Object.entries(commandIds))for(const id of ids)if($(id)){groups[k].push($(id));allCommands.append($(id));}
 const quick=document.createElement('div');quick.className='workspace-quick';for(const id of ['undo','redo','cad-assets-open','cad-ai-open','cad-material-chip'])if($(id))quick.append($(id));
 const tabs=document.createElement('div');tabs.className='workspace-modes';for(const[key,label]of [['edit','编辑'],['draw','草图'],['model','建模'],['site','场地']]){const b=document.createElement('button');b.dataset.workspace=key;b.textContent=label;b.onclick=()=>selectCategory(key);tabs.append(b);}
 const focus=document.createElement('button');focus.id='workspace-focus';focus.textContent='专注视图';focus.title='最大化视口 / 恢复布局';focus.onclick=()=>{document.body.classList.toggle('viewport-focus');focus.textContent=document.body.classList.contains('viewport-focus')?'恢复布局':'专注视图';};quick.append(focus);
 bar.replaceChildren(tabs,allCommands,quick,$('cad-active-tool'));function selectCategory(key){for(const b of tabs.children)b.classList.toggle('active',b.dataset.workspace===key);for(const[k,buttons]of Object.entries(groups))for(const b of buttons)b.hidden=k!==key;}selectCategory('edit');
 const panels=[{node:$('construction-panel'),close:construction.close},{node:$('designer-panel'),close:designer.close},{node:$('direct-edit-bar'),close:direct.cancel},{node:$('measurement-panel'),close:measurement.close}];
 for(const p of panels){p.node.classList.add('workspace-task-panel');tasks.append(p.node);}
 for(const id of ['cad-modify-dialog','cad-build-dialog','cad-component-dialog','cad-advanced-dialog','cad-site-dialog','cad-history-dialog']){const node=$(id);node.classList.add('workspace-task-panel','workspace-dialog');tasks.append(node);panels.push({node,close:()=>node.close()});}
 const visible=p=>p.node.tagName==='DIALOG'?p.node.open:!p.node.hidden;let current=null;
 const observer=new MutationObserver(records=>{const opened=records.map(r=>panels.find(p=>p.node===r.target)).filter(p=>p&&visible(p)).at(-1);if(opened&&opened!==current){current=opened;for(const p of panels)if(p!==opened&&visible(p))p.close();document.body.classList.remove('viewport-focus');focus.textContent='专注视图';tasks.scrollTop=0;}if(current&&!visible(current))current=null;current||=panels.find(visible)||null;tasks.hidden=!current;defaults.hidden=!!current;right.dataset.editing=current?.node.id||'';});
 for(const p of panels)observer.observe(p.node,{attributes:true,attributeFilter:['hidden','open']});
 function group(title,parent,ids,open=false){const nodes=[...new Set(ids.map(id=>$(id)?.closest('label')||$(id)).filter(Boolean))];if(!nodes.length)return;const details=document.createElement('details');details.className='workspace-section';details.open=open;details.innerHTML='<summary></summary>';details.firstChild.textContent=title;parent.append(details);for(const node of nodes)details.append(node);return details;}
 const figure=$('figure-controls');$('figure-plane').closest('.row').after($('sketch-plane-lock').closest('label'));group('精确坐标',figure,['figure-points','figure-add','sketch-node-tools']);group('材料与方块形态',figure,['figure-voxel','figure-surface','figure-material','figure-slab','figure-stairs']);group('与地形衔接',figure,['figure-terrain','figure-offset','figure-spacing']);
 // Confirmation stays visible at the foot of the fixed panel.
 for(const [panel,id]of [[$('construction-panel'),'construction-apply'],[$('designer-panel'),'designer-apply']]){const row=$(id).parentElement;row.classList.add('workspace-confirm');if(id==='construction-apply'){const report=$('construction-report');report.classList.add('workspace-result');row.prepend($('sketch-snap-feedback'),report);}panel.append(row);}
 $('construction-preview').textContent='重新校准';$('construction-preview').title='参数会自动更新预览';$('construction-close').textContent='取消';$('designer-close').textContent='取消';$('direct-cancel').textContent='取消';
 $('workspace-shelf-close').onclick=()=>dock('objects');
 return{showDock(name){$('dock-objects').hidden=false;shelf.hidden=name==='objects';$('workspace-shelf-preview').hidden=name!=='assets';if(name==='assets')$('asset-detail').hidden=false;},openDialog(dialog){if(!dialog.classList.contains('workspace-dialog'))return false;construction.close();designer.close();direct.cancel();dialog.setAttribute('open','');return true;},selectCategory};
}
